### ISSUE TITLE
Buffer timeout with HashSet does not follow the max size parameter

### ISSUE THREAD

**Issue by mkluzacek** [reactor/reactor-core#3211] opened 2022-10-03 14:04 UTC
Hi when using the bufferTimeout with HashSet the function actually counts the "on next triggers" instead of checking the size of the buffer causing it to emit a partial buffer when distinct values are present.

We are reading infinite stream of RabbitMQ messages and looking for a way to easily filter duplicates. We could just buffer it and then filter it manually but thats not really optimal.

Not sure if its possible to "fix" this or not. Will be glad for any response or suggestion on how to do this.

## Expected Behavior
The function should check the size of the provided buffer instead of counting "on next triggers"

## Actual Behavior
The "on next triggers" are counted instead of checking the buffer size.

## Steps to Reproduce
```java
@Test
void reproCase() {
Flux.just(1,1,1,2,2,3,4,5,6,6,6)
        .bufferTimeout(6, Duration.ofSeconds(10), HashSet::new)
        .map(
            integer -> {
              System.out.println("Result: " + integer);
              return integer;
            }
        )
        .subscribe();
}
```
This prints:
Result: [1, 2, 3]
Result: [4, 5, 6]
Instead of the expected:
Result: [1,2,3,4,5,6]

## Your Environment
reactor-core:3.4.5
Java 11

**Comment by chemicL** [comment] 2022-10-04 12:29
Actually, I'm not sure whether this would work as expected either with the way you described it. With the case you provided, the implementation would yield:

    Result: [1,2,3,4,5,6]
    Result: [6] // caused by timeout or followed by other values (possibly duplicates of values present in the previous buffers)
    
As you can see, the way the operator works is by instantiating a new collection via the provided `Supplier` every time a new buffer is started. I'd say it's worth describing the actual ramifications you have and asking a question on StackOverflow, where multiple potential solutions can be discussed. The time aspect is not described in the initial report, but I assume also has significance.

Closing the issue for now, as it does not apply to the mentioned operator. Perhaps with some deeper analysis of the problem in hand, a new operator might be necessary, but I suppose the existing ones can be combined to provide a performant solution. Just need more details to pick the combination.

**Closed by chemicL** 2022-10-04 12:29 UTC
Labels: :question:need-triage
