### ISSUE TITLE
Improve UnicastProcessor sink() strategies application

### ISSUE THREAD

**Issue by osi** [reactor/reactor-core#612] opened 2017-05-18 19:19 UTC
When using `FluxProcessor#sink(OverflowStrategy)`, the strategy is ignored if `FluxProcessor#getBufferSize` is `Integer.MAX_VALUE`, the default return value of the method.

If a `UnicastProcessor` is created with a custom queue that is bounded, it does not override that method, which makes it impossible to apply a custom overflow strategy.

(My case is that I was supplying a queue of one, and trying to use the LATEST overflow strategy)

**Comment by smaldini** [comment] 2017-05-20 00:06
the capacity is somehow infinite as its request hints : request(Long.MAX). 
UnicastProcessor is a specific beast tho it was intended to help operator or similar create a simple bridge, meaning that usually you can append onBackpressureLatest instead of pre-envitively doing it. It would be roughly equivalent in fact.

I think the corollary point then is that maybe our strategy could be that we map specifically for UnicastProcessor the strategies into the onBackpressure variants directly.

**Comment by osi** [comment] 2017-05-22 12:44
ah good point about the request. yes what you describe would be equivalent. your enhancement idea is good - i was surprised at runtime when it didn't act as i intuited from the available API calls.

**Comment by simonbasle** [comment] 2017-06-19 09:28
quickly looking at it, the strategy of trying to apply a onBackpressureXXX operator to the 'UnicastProcessor` when calling `sink(strategy)` is not applicable as is, since the `Sink` isn't a `Flux` (so it doesn't have the `onBackpressureXXX` operators) and applying the operator _before_ calling sink doesn't work either (it cannot change the variable the processor is assigned to, and once onBackpressure is called there's no `sink()` method to invoke anymore.

@smaldini @osi I think we are stuck with the current state of affairs, and having to call `onBackpressureXXX` manually on a `UnicastProcessor`... maybe we can output a warning or something? maybe even an `IllegalArgumentException` when calling `UnicastProcessor.sink(anythingElseThanIGNORE)`? (although that would probably mean to remove the `final` from `FluxProcessor.sink` )

**Comment by osi** [comment] 2017-06-19 13:39
i discovered this when my application was running, which is the worst time to discover it.

if it could be moved to initialization time by throwing an `IllegalArgumentException` I think that's an improvement. i think the code could just live in `FluxProcessor#sink(strategy)`, and just complain if the buffer is infinite and the strategy isn't `IGNORE` (as other processors might be susceptible)

**Comment by smaldini** [comment] 2017-07-06 19:15
Maybe we can provide an alternative resolution here for now which could be to simply not return MAX_VALUE for bufferSize if the queue is not the default unbounded reactor one.

**Comment by simonbasle** [comment] 2017-07-07 08:52
But what would it return @smaldini? `BlockingQueue` in the JDK has a `remainingCapacity()` method that returns the queue's capacity or `Integer.MAX_VALUE` if unbounded, but @osi your custom queue is probably not extending that, is it?

So should we try to detect bounded vs unbounded `BlockingQueue`?

Suggestion:
- `BlockingQueue`: return `remainingCapacity()`
- `SpscLinkedArrayQueue`: return `Integer.MAX_VALUE`
- `SpscArrayQueue`: return `length()`
- others: return `Integer.MAX_VALUE - 1` (eg. as constant `UNSURE`?)

**Comment by osi** [comment] 2017-07-07 12:25
The custom queue I had used when encountering this was a fixed size queue from `reactor.util.concurrent.QueueSupplier`

**Comment by simonbasle** [comment] 2017-07-10 16:30
Ok so here's the plan:
 - [ ] Add a `QueueSupplier#CAPACITY_UNSURE` int constant, value `Integer.MIN_VALUE`
 - [ ] Add a util method to `QueueSupplier` to attempt to detect the capacity of a queue
   - `BlockingQueue`: return `remainingCapacity()`
   - `SpscLinkedArrayQueue`: return `Integer.MAX_VALUE`
   - `SpscArrayQueue`: return `length()`
   - others: return `CAPACITY_UNSURE`
- [ ] Use the util method in `UnicastProcessor#getBufferSize()`

**Closed** 2017-07-13 16:45 UTC
Labels: enhancement, ideal for contribution
