### ISSUE TITLE
Prefetch summing

### ISSUE THREAD

**Issue by bsideup** [reactor/reactor-core#1392] opened 2018-10-19 07:52 UTC
### Expected behavior
?

### Actual behavior
Prefetches are summed

### Steps to reproduce
```java
AtomicLong requests = new AtomicLong();
CountDownLatch latch = new CountDownLatch(1);
Flux.range(0, Integer.MAX_VALUE)
        .doOnRequest(requests::addAndGet)
        .compose(flux -> {
            for (int i = 0; i < 10; i++) {
                flux = flux.concatMap(Mono::just, 1);
            }
            return flux;
        })
        .subscribe(new Subscriber<>() {
            @Override
            public void onSubscribe(Subscription s) {
                s.request(1);
            }

            @Override
            public void onNext(Integer integer) {
                latch.countDown();
            }

            @Override
            public void onError(Throwable t) {

            }

            @Override
            public void onComplete() {

            }
        });

latch.await(5, TimeUnit.SECONDS);

Assert.assertEquals(1, requests.get());
```

### Reactor Core version
3.2.1.RELEASE

### JVM version (e.g. `java -version`)
Any

**Comment by OlegDokuka** [comment] 2018-10-19 07:56
As we discussed with @bsideup. We need to include to the following clause:
```
onSusbscribe(s) {
 ... 
 s.request(Operators.unboundedOrPrefetchOrRequested(prefetch, requested));
}
```

which in case of `prefetch > requested` should request only `prefetch`, in case of `requested > prefetch` -> `requested`.

cc/ @akarnokd

**Comment by simonbasle** [comment] 2018-10-19 11:36
@OlegDokuka `onSubscribe` can and will be invoked _before_ any `request` has been sent though... not sure this solves anything.

Not sure we can safely compare the `consumed` vs `inner.requested` amount in the drain loop of `FluxConcatMap` to avoid the [replenish there](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/FluxConcatMap.java#L388) either.

**Comment by OlegDokuka** [comment] 2018-10-19 13:58
Yeah, agree. Missed that part.

**Comment by bsideup** [comment] 2020-07-01 10:16
We just merged #2202 that allows a workaround here (no prefetch == no summing :D)

**Comment by simonbasle** [comment] 2021-02-18 09:56
Prefetching was a tradeoff that was made at project inception, which is hard to change now. As soon as 1-to-N operators like concatMap or flatMap are used, prefetching compounds with request re-patterning these operators necessarily do and the upstream request patterns become less predictable. That's the tradeoff, in exchange for better performance without tuning.

Perhaps a different tradeoff would be made today (predictability of requests upstream, lifecycle management with deeper integration of discarding, ...) but that's such a deep change, it would effectively represent a fourth generation of Reactor.

Closing this, but research into that direction is on the table for 4.0.0

**Closed by simonbasle** 2021-02-18 09:56 UTC
Labels: status/on-hold

**Comment by bsideup** [comment] 2021-02-18 10:11
errr.... but why closing? This **is** an issue, it is there and not fixed. Prefetch is an optimization, but over-requesting is a _problem_.

**Comment by OlegDokuka** [comment] 2021-02-18 10:13
Can we probably keep it open while there is an ongoing research in progress?

**Comment by simonbasle** [comment] 2021-02-18 10:15
Isn't it superseded by #1397 for the larger research part?

> but over-requesting is a problem.

why would it be _intrisically_ wrong? as long as the downstream request is respected.

**Comment by bsideup** [comment] 2021-02-18 10:27
#1397 is a different problem around the same root cause. It may happen that one gets fixed but not another.

> why would it be intrisically wrong? as long as the downstream request is respected.

You're thinking in-memory. Add RSocket/R2DBC/reactor-kafka or any other IO source and these extra prefetches are going to cost $$$

**Comment by simonbasle** [comment] 2021-02-18 10:36
I think the 0-prefetch clutch is the best we can do in current maintenance versions, so the symptom fix is to switch to 0-prefetch version of `concatMap` (see also the reworkd around `switchMap` in the same direction).

Perhaps we should open a new more general issue around different prefetch tradeoff research, but I was under the impression #1397 would be a good fit for an epic-style tracker of the root cause.

**Comment by bsideup** [comment] 2021-02-18 10:45
IMO closing this issue sends a wrong message because it is not fixed and the workarounds are rather (don't do X)

Also, some may find the same bug and open a new issue because this one is closed :)
