### ISSUE TITLE
Block operation with BoundedScheduledExecutorService.ensureQueueCapacity method

### ISSUE THREAD

**Issue by ssalamov** [reactor/reactor-core#2952] opened 2022-03-09 13:53 UTC
Hello,

Could you please assist with this issue? BlockHound detected the below block operation:

```
java.lang.Error: jdk.internal.misc.Unsafe#park
	at com.ocado.lineitems.config.util.internal.LineitemsBlockHoundIntegration.lambda$applyTo$0(LineitemsBlockHoundIntegration.java:14)
	at reactor.blockhound.BlockHound$Builder.lambda$install$8(BlockHound.java:427)
	at reactor.blockhound.BlockHoundRuntime.checkBlocking(BlockHoundRuntime.java:89)
	at java.base/jdk.internal.misc.Unsafe.park(Unknown Source)
	at java.base/java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(Unknown Source)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(Unknown Source)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(Unknown Source)
	at java.base/java.util.concurrent.locks.ReentrantLock.lock(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.size(Unknown Source)
	at reactor.core.scheduler.BoundedElasticScheduler$BoundedScheduledExecutorService.ensureQueueCapacity(BoundedElasticScheduler.java:642)
	at reactor.core.scheduler.BoundedElasticScheduler$BoundedScheduledExecutorService.submit(BoundedElasticScheduler.java:744)
	at reactor.core.scheduler.Schedulers.workerSchedule(Schedulers.java:1344)
	at reactor.core.scheduler.ExecutorServiceWorker.schedule(ExecutorServiceWorker.java:50)
	at reactor.core.publisher.FluxSubscribeOn.subscribeOrReturn(FluxSubscribeOn.java:62)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4385)
	at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:128)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
```

Regards,
Samir Salamov

**Comment by simonbasle** [comment] 2022-03-09 14:09
This should be resolved by https://github.com/reactor/reactor-core/pull/2909, marking as duplicate.
As stated in both the above PR and the associated issue, I don't think there's anything we can do about that one other than adding it to the blockhound exceptions.
Otherwise, the bounded aspect of the scheduler cannot be guaranteed easily without a risk of losing track of tasks that were pending and then got executed.

**Comment by simonbasle** [comment] 2022-03-09 14:09
Duplicate of #2909

**Closed** 2022-03-09 14:09 UTC
Labels: status/duplicate

**Comment by ssalamov** [comment] 2022-03-09 15:50
@simonbasle thank you for info. Could you please clarify when https://github.com/reactor/reactor-core/pull/2909 going to be released?
