### ISSUE TITLE
Flux.generator with parallel support

### ISSUE THREAD

**Issue by laxika** [reactor/reactor-core#2026] opened 2020-01-30 10:15 UTC
I'm creating a Flux using Flux.generate(). The generator (Consumer) is actually reading from a message queue. The problem is that this call takes quite a long time (occasionally 1-2 seconds even). This will make the flux to stop processing.

## Motivation

```java
package com.github.loa.vault.service.listener;

import com.github.loa.document.service.domain.DocumentType;
import com.github.loa.queue.service.QueueManipulator;
import com.github.loa.queue.service.domain.Queue;
import com.github.loa.queue.service.domain.message.DocumentArchivingMessage;
import com.github.loa.vault.service.domain.DocumentArchivingContext;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import reactor.core.publisher.SynchronousSink;

import java.util.function.Consumer;

@Slf4j
@Service
@RequiredArgsConstructor
public class VaultQueueConsumer implements Consumer<SynchronousSink<DocumentArchivingContext>> {

    private final QueueManipulator queueManipulator;

    @Override
    public void accept(final SynchronousSink<DocumentArchivingContext> documentSourceItemSynchronousSink) {
        final DocumentArchivingMessage documentArchivingMessage = (DocumentArchivingMessage)
                queueManipulator.readMessage(Queue.DOCUMENT_ARCHIVING_QUEUE);

        documentSourceItemSynchronousSink.next(
                DocumentArchivingContext.builder()
                        .type(DocumentType.valueOf(documentArchivingMessage.getType()))
                        .source(documentArchivingMessage.getSource())
                        .content(documentArchivingMessage.getContent())
                        .build()
        );
    }
}
```

Obviously adding `parallel` doesn't help because the generator is still being called one at a time.

```java
Flux.generate(vaultQueueConsumer)
    .parallel()
    .runOn(Schedulers.elastic()) 
    .flatMap(vaultDocumentManager::archiveDocument)
    .subscribe();
```

I don't want to use Flux.create() because then I would lose backpressure.

Fired a question on StackOverflow with multiple bounties but only got some subpar solutions:
https://stackoverflow.com/questions/59708845/preload-elements-for-flux-generate

## Desired solution
```java
Flux.generateParallel(...)
Flux.generateParallel(..., 10)
```

Or something similar would be good.

## Considered alternatives
```java
Mono.just(1).repeat()  // create infinite flux, maybe there is a nicer way for that?
    .flatMap(this::readFromQueue, 100) // define queue polling concurrency
    .flatMap(this::archiveDocument)
    .subscribe();
```
```java
private Mono<String> readFromQueue(Integer ignore) {
    return Mono.fromCallable(() -> {
        Thread.sleep(1500); // your actual blocking queue polling here
        return "queue_element";
    }).subscribeOn(Schedulers.elastic()); // dedicate blocking call to threadpool
}
```

**Comment by bsideup** [comment] 2020-01-30 10:37
Duplicate of #1596

**Closed** 2020-02-06 10:57 UTC
Labels: status/duplicate

**Comment by simonbasle** [comment] 2020-02-06 10:59
@laxika please chime in #1596 if you have particular ideas around what a generic polling operator's interface could look like (free of the shackles of current `generate`/`create`/etc... but if concepts and interfaces like the `Sink` can be reused, all the better)
