### ISSUE TITLE
Flaky tests on Windows when using Mono.timeout

### ISSUE THREAD

**Issue by wilkinsona** [reactor/reactor-core#2297] opened 2020-08-01 07:18 UTC
## Expected Behavior
Mono.timeout works consistently.

## Actual Behavior
I’m seeing a test failure in Boot’s CI on Windows where it looks as if a `Mono.timeout(timeout, fallback)` is falling back before the timeout has elapsed. The timeout in the test is 100ms so it should take at least 100ms to run and it does on my Mac. When it failed on Windows, the test completed in 79ms, hence my suspicion that the timeout popped too soon. I’ve only seen it fail on Windows.

## Steps to Reproduce

[This](https://github.com/spring-projects/spring-boot/blob/7d25948ab5f0e86d31de1a8c7f1126192f1aa029/spring-boot-project/spring-boot-actuator/src/test/java/org/springframework/boot/actuate/health/CompositeReactiveHealthIndicatorTests.java#L71-L84) is the test that's failing and you can see some example failures [here](https://ge.spring.io/s/mxrhac3vqpu6c/tests/:spring-boot-project:spring-boot-actuator:test/org.springframework.boot.actuate.health.CompositeReactiveHealthIndicatorTests/timeoutReachedUsesFallback()#1).

I've attempted to reproduce the problem with something minimal, and this fails in a quite similar way a few times in 100 in a Windows VM:

```java
@Test
@RepeatedTest(100)
void timeoutWorksAsExpected() {
	Mono<StringBuffer> result = Flux.fromIterable(Arrays.asList("a", "b"))
			.flatMap((entry) -> Mono.delay(Duration.ofMillis((entry.equals("a") ? 10000 : 10))).map((l) -> entry)
					.transformDeferred((mono) -> mono.timeout(Duration.ofMillis(100), Mono.just("z"))))
			.collect(StringBuffer::new, (buffer, string) -> buffer.append(string));
	StepVerifier.create(result).consumeNextWith((builder) -> {
		assertThat(builder.toString()).isEqualTo("bz");
	}).verifyComplete();
}
```

## Your Environment
The CI failures are on Windows Server 2016 10.0 with Reactor 3.3.8.RELEASE running on AdoptOpenJDK 1.8.0_212-b03.

**Comment by wilkinsona** [comment] 2020-08-03 13:24
We're also seeing the failure with Reactor 3.4.0.M1. [Here's the build scan]( https://ge.spring.io/s/ufmzizu62g5xi/tests/:spring-boot-project:spring-boot-actuator:test/org.springframework.boot.actuate.health.CompositeReactiveHealthIndicatorTests/timeoutReachedUsesFallback()#1).

**Comment by simonbasle** [comment] 2020-08-05 10:40
`Mono.timeout` and `Mono.delay` are fairly straightforward, so I doubt this is an issue with Reactor itself, but probably the `ScheduledExecutorService` and underlying `System.nanoTime()`/`System.currentTimeMillis()` implementations on Windows (maybe combined with the VM hypervisor?)

That said, just to be sure it is linked to the delay or timeout, the test above can be further simplified with a removal of the `transformDeferred` (you can directly apply the `.timeout` to the `Mono.delay(Duration.ofMillis((entry.equals("a") ? 10000 : 10))).map((l) -> entry)`. Can you test with that simplification?

**Comment by wilkinsona** [comment] 2020-08-05 11:44
It's hard to say if it's made a difference, unfortunately. I originally discussed the problem with @bsideup in March. I've moved to a new laptop and a new Windows VM since then. I've seen the test as shown above fail once in several runs. I haven't seen it fail at all without `transformDeferred` but the failure rate with it isn't high enough to be sure that means anything.

**Comment by wilkinsona** [comment] 2020-08-05 11:48
The test on CI fails fairly often. It might be worth you asking Trevor if you can get remote desktop access to the worker and run some experiments there.

**Comment by wilkinsona** [comment] 2020-08-12 18:26
The test in Boot [failed again today](https://ge.spring.io/s/rbe5x7hhozjmk/tests/:spring-boot-project:spring-boot-actuator:test/org.springframework.boot.actuate.health.CompositeReactiveHealthIndicatorTests/timeoutReachedUsesFallback()#1).

**Comment by bsideup** [comment] 2020-08-17 13:42
I was able to reproduce the issue. While debugging I also figured that, on Windows, under heavy load, the timers have a very low precision. e.g. this test fails when I run it and some CPU stress test:
```java
@RepeatedTest(1000)
void windowsTimersPrecision() throws Exception {
	Scheduler scheduler = Schedulers.parallel();

	long nanoTime = System.nanoTime();
	FutureTask<Long> task = new FutureTask<>(System::nanoTime);

	scheduler.schedule(task, 50, TimeUnit.MILLISECONDS);
	Long resolvedAt = task.get();

	assertThat(resolvedAt - nanoTime).isLessThan(TimeUnit.MILLISECONDS.toNanos(150));
}
```

Since we don't have our own timers logic and delegate everything to JVM (via `ScheduledExecutorService#schedule`), I am not really sure we can do anything here.

What I allso noticed is that the `windowsTimersPrecision` test was passing if I use "isLessThan 200ms" assertion.
@wilkinsona you may consider playing with the timeout values you use, given this knowledge.

**Comment by wilkinsona** [comment] 2020-09-01 10:16
I made the suggested changes to the test in Boot on 26 August. At the time of writing its has passed 5 times since then and has yet to fail. That's pretty good compared to [its recent behaviour](https://ge.spring.io/scans/tests?list.size=50&list.sortColumn=startTime&list.sortOrder=desc&search.buildToolTypes=gradle&search.buildToolTypes=maven&search.relativeStartTime=P90D&search.rootProjectNames=spring-boot-build&search.tags=Windows%20Server%202016&search.timeZoneId=Europe/London&tests.container=org.springframework.boot.actuate.health.CompositeReactiveHealthIndicatorTests&tests.sortField=FLAKY&tests.test=timeoutReachedUsesFallback()&tests.unstableOnly=true). We'll keep an eye on it, but the initial signs are looking hopeful.

**Comment by bsideup** [comment] 2020-11-09 11:15
@wilkinsona do you think we can close this issue now? :)

**Comment by wilkinsona** [comment] 2020-11-09 11:31
Thanks for the nudge. I'd forgotten to check the test results. I've just done that now and it's certainly better, but there has still been two flakey failures since 26 August. Perhaps I should further widen the timeout? It's [250ms now](https://github.com/spring-projects/spring-boot/commit/04540887af1dcf4c38794d08a556b57efbf4057f).

**Closed** 2022-06-09 13:50 UTC
Labels: status/on-hold, for/user-attention
