### ISSUE TITLE
Integrate Scheduler with java.time

### ISSUE THREAD

**Issue by thekalinga** [reactor/reactor-core#1384] opened 2018-10-13 17:00 UTC
`java.time` is a good API to work with dates & times. However, since reactor `Scheduler` abstracts the clock, using APIs like `LocalDateTime.now()` is a pain as it uses system clock, especially in reactor tests that use virtual clock

`java.time` has a notion of clock that allows users to provide our own version of `java.time.Clock`. So, I created a new `Clock` called `SchedulerClock` which is backed by `Scheduler`

```java
package reactor.core.scheduler;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneId;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

import static java.time.Instant.ofEpochSecond;
import static java.util.concurrent.TimeUnit.MILLISECONDS;
import static java.util.concurrent.TimeUnit.NANOSECONDS;
import static java.util.concurrent.TimeUnit.SECONDS;

public class SchedulerClock extends Clock {

  private static final Map<Integer, SchedulerClock> hashToCachedInstance = new ConcurrentHashMap<>();

  private final Scheduler scheduler;
  private final ZoneId zone;

  public static SchedulerClock getInstance(Scheduler scheduler, ZoneId zone) {
    int hash = hash(scheduler, zone);
    if (hashToCachedInstance.get(hash) == null) {
      hashToCachedInstance.putIfAbsent(hash, new SchedulerClock(scheduler, zone));
    }
    return hashToCachedInstance.get(hash) ;
  }

  private static int hash(Scheduler scheduler, ZoneId zone) {
    return Objects.hash(scheduler, zone);
  }

  private SchedulerClock(Scheduler scheduler, ZoneId zone) {
    this.scheduler = scheduler;
    this.zone = zone;
  }

  @Override
  public ZoneId getZone() {
    return zone;
  }

  @Override
  public SchedulerClock withZone(ZoneId newZone) {
    if (newZone.equals(this.zone)) {  // intentional NPE
      return this;
    }
    return new SchedulerClock(scheduler, newZone);
  }

  @Override
  public long millis() {
    return scheduler.now(MILLISECONDS);
  }

  @Override
  public Instant instant() {
    long nowInNanos = scheduler.now(NANOSECONDS);
    long nowInSeconds = SECONDS.convert(nowInNanos, NANOSECONDS);
    long nanoAdjustment = nowInNanos - NANOSECONDS.convert(nowInSeconds, SECONDS);
    return ofEpochSecond(nowInSeconds, nanoAdjustment);
  }

  @Override
  public int hashCode() {
    return hash(scheduler, zone);
  }

  @Override
  public boolean equals(Object o) {
    if (this == o)
      return true;
    if (o == null || getClass() != o.getClass())
      return false;
    SchedulerClock that = (SchedulerClock) o;
    return Objects.equals(scheduler, that.scheduler) && Objects.equals(zone, that.zone);
  }

  @Override
  public String toString() {
    return "SchedulerClock[" + scheduler + "," + zone + "]";
  }
}
```

This also requires these two new methods to `Scheduler` class

```java
	/**
	 * @return the current clock that's backed by this scheduler
	 */
	default Clock clock() {
		return SchedulerClock.getInstance(this, ZoneId.systemDefault());
	}

	/**
	 * @return the current clock that's backed by this scheduler
	 */
	default Clock clock(ZoneId zone) {
		return SchedulerClock.getInstance(this, zone);
	}
```

Once we have this in place, everyone can use `LocalDateTime.now(scheduler.clock())` in their code to get hold of now instead of using the real system time

I believe this should be part of the library. With this everyone can work with existing `java.time` api with lil less friction

**Comment by simonbasle** [comment] 2018-10-15 07:46
duplicate of #920, this has been fixed in addons (`reactor-extra` dependency) via reactor/reactor-addons#132

**Closed by simonbasle** 2018-10-15 07:46 UTC
Labels: duplicate, wontfix

**Comment by thekalinga** [comment] 2018-10-15 08:05
@simonbasle Thanks. Dint know it existed :>

Would be great if the clocks are cached & even better exposed via `Scheduler` interface

**Comment by simonbasle** [comment] 2018-10-15 08:09
One possible way of doing this is to have the addons' `SchedulerClock` implement `Scheduler` itself and delegate all of its methods. This way you could keep the `SchedulerClock` reference around instead of the underlying `Scheduler`. Wdyt?

**Comment by thekalinga** [comment] 2018-10-15 08:29
And the only safe way for the user to use this `Scheduler` with `Clock` API is to pass around `SchedulerClock` instead of `Scheduler` which is an implementation detail we should not be passing on to the user

Otherwise he will be forced to do `instanceof` checks on the `Scheduler` he received from `Schedulers`

Its better to make sure that user does not know that there is a class called `SchedulerClock` as it will become an overhead on the API

**Comment by simonbasle** [comment] 2018-10-15 08:39
Once the addons' `SchedulerClock` both implements `Scheduler` and extends `Clock` (unfortunately java 8 `Clock` isn't an interface), the usage could look like this:

```java
public class MyClass {

  private final SchedulerClock schedulerAndClock;

  public MyClass(Scheduler toUse) {
    this.schedulerAndClock = SchedulerClock.withScheduler(toUse);
  }

  public Scheduler getScheduler() { return schedulerAndClock; }

  public Clock getClock() { return schedulerAndClock; }

}
```

Not everybody is interested in the `Clock` aspect of the `Scheduler` though, as most of the time the `Schedulers` are passed around to methods like `publishOn`, not java 8 time. If a user is interested in the `Clock` aspect, then by all means let that user create a `SchedulerClock` and pass it around... It is not an implementation detail at this point. 

Adding methods to the base contract of `Scheduler` is something we'd like to avoid, unless a significant portion of the user base demands it. The alternative of wrapping the `Scheduler` in a `SchedulerClock` is good enough. That's 100% the same as the approach you demonstrated in your snippet btw.

Adding a field to every scheduler implementation for the purpose of caching a `Clock` view of the `Scheduler` is *definitely* out of the picture.

Having every `Scheduler` implementation _extend_ `Clock` is not possible either.

**Comment by thekalinga** [comment] 2018-10-15 08:40
If we chose to wrap every `Scheduler` in this new `SchedulerClock`, this is an unnecessary cost of indirection as we don't know which one the user wants wrapped, which one he does not

**Comment by simonbasle** [comment] 2018-10-15 08:40
Who said anything about wrapping every `Scheduler`?

**Comment by thekalinga** [comment] 2018-10-15 08:41
Sorry.. I got your previous update after I posted this comment :D Thanks github

**Comment by thekalinga** [comment] 2018-10-15 08:48
@simonbasle

The wrapping of `Scheduler` & `Clock` can be avoided altogeather if the `SchedulerClock.of` in `reactor-extras` caches instances internally

w.r.t API change, I agree that this is useful if there is a demand for it & the API is natural to be there. This is a call you are in a better position to take

**Comment by simonbasle** [comment] 2018-10-15 08:52
Let's not try to be too smart. Again, it is up to the user to obtain a `Clock` and decided wether or not its usage warrants keeping it around (eg. in a cache or instance variable) vs consuming and discarding it immediately.

One intermediate solution if the `SchedulerClock` is made to implement `Scheduler` would be to ensure the factory method detects a `SchedulerClock` parameter and immediately returns it instead of further wrapping.

**Comment by thekalinga** [comment] 2018-10-15 09:07
> Let's not try to be too smart. Again, it is up to the user to obtain a Clock and decided wether or not its usage warrants keeping it around (eg. in a cache or instance variable) vs consuming and discarding it immediately.

Yes.. You are right.. I dont think about the life span of the `Clock` from the user's point of view. At the same time, we dont know if he wants a cached instance as he uses it a lot in his code base

One way to handle this is to have a factory that explicitly caches `SchedulerClock` like `SchedulerClocks.getInstance` vs `SchedulerClocks.newInstance` which does no caching. This way user can ask what he wants at runtime

> One intermediate solution if the SchedulerClock is made to implement Scheduler would be to ensure the factory method detects a SchedulerClock parameter and immediately returns it instead of further wrapping

`SchedulerClock` can be made to return `Scheduler`, this way, we rely on composition rather than inheritance & still achieve this

**Comment by thekalinga** [comment] 2018-10-15 09:09
> SchedulerClock can be made to return Scheduler, this way, we rely on composition rather than inheritance & still achieve this

I'm wrong on this

**Comment by thekalinga** [comment] 2018-10-15 12:42
@simonbasle What do u think?

**Comment by simonbasle** [comment] 2018-10-15 15:40
I think the current `SchedulerClock` API is just fine, so until proven there is a very strong need for something more integrated I'm not going to integrate it in core. Implementing the caching of clock instances is not something we want to do at this level either.

Only improvement I think makes sense is to let `SchedulerClock` implement `Scheduler` and have its factory method be guarded with an `instanceof` check (in order to avoid nested wrapping).

**Comment by thekalinga** [comment] 2018-10-16 10:13
Ok.. Thanks
