### ISSUE TITLE
Mono never complete with combinaison of Flux.merge, delayUntil and Mono.empty

### ISSUE THREAD

**Issue by Tiller** [reactor/reactor-core#2597] opened 2021-02-08 11:31 UTC
While writing a unit test, I ran into an issue where a publisher of mine never completed. While trying to find out the origin, I rewrote and simplified my workflow several times to end up with:

```java
      System.err.println(Flux.merge(
              Mono.empty(),
              Mono
                      .just("A")
                      .filter(s -> false)
                      .delayUntil(s -> Mono.empty())
                      //.doFinally(s -> System.err.println("finally"))
          )
          .collectList()
          .block());
```

## Expected Behavior
The mono should complete with an empty list

## Actual Behavior
The mono never complete and the call hangs forever

I don't know what precisely is the issue but:
1. uncommenting the `doFinally` fixes the issue
2. removing the `delayUntil` fixes the issue
3. removing the `Mono.empty()` in the `Flux.merge` to only leave one parameter fixes the issue
4. adding `.map(a -> a)` after the `delayUntil` fixes the issue

## Your Environment
* Reactor version(s) used: 3.4.1
* JVM version: OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.10)
* OS and version: Ubuntu 20.10 5.8.0-41-generic

**Comment by simonbasle** [comment] 2021-02-08 17:15
There seem to be a bug indeed. As a workaround, you can append a `.hide()` to the second publisher inside the `merge`.

**Comment by simonbasle** [comment] 2021-02-08 17:17
The root cause seem to be in the `MonoDelayUntil.DelayUntilCoordinator#onComplete()` method: when fused, the operator doesn't pick up that the source is instantaneously resolved as empty, and never triggers the `onComplete` downstream.

**Comment by simonbasle** [comment] 2021-02-08 17:24
NB: This affects `3.3.x` branch as well, and should be fixed there to start with.

**Closed** 2021-03-18 10:16 UTC
Labels: status/has-workaround, type/bug
