### ISSUE TITLE
Mono/single/replay/refCount facilitates to the occurrence of java.util.concurrent.CancellationException

### ISSUE THREAD

**Issue by denyshorman** [reactor/reactor-core#1650] opened 2019-04-06 21:34 UTC
### Expected behavior
Stream produces expected error.

### Actual behavior
Stream produces CancellationException error.

### Steps to reproduce
Code that produces CancellationException:
```kotlin
val stream = Flux.merge(Flux.just(1), Flux.never())
    .scan(0) { state, delta -> state + delta }
    .skip(1)
    .replay(1)
    .refCount()

Flux.never<Int>()
    .takeUntilOther(
        Mono.zip(Mono.just(1), stream.take(1).single())
            .flatMap<Int> { Mono.error(Exception("error")) }
            .takeUntilOther(stream.filter { it == 0 }.take(1))
            .repeatWhen { stream.onBackpressureLatest().filter { it > 0 } }
            .ignoreElements()
    )
    .subscribe(
        {println(it)},
        {println(it)},
        {println("completed")}
    )
```

If you replace:
```Mono.zip(Mono.just(1), stream.take(1).single())```
to
```Flux.zip(Mono.just(1), stream.take(1))```
stream correctly produces expected exception **java.lang.Exception: error**.

Adding grace period to `.refCount(1, Duration.ofNanos(1))` of `stream` variable also helps to fix the issue.

Another example that produces CancellationException:

```kotlin
var x = Flux.never<Int>()
fun xx() = x

val z = Flux.range(1, 10)
    .takeUntilOther(Flux.defer{xx().takeUntil{it == 7}.ignoreElements()})
    .share()

x = z

xx().subscribe({println(it.toString())}, {println(it.toString())}, {println("completed")})
```

### Reactor Core version
3.2.8.RELEASE

### JVM version (e.g. `java -version`)
11.0.1

### Logs
<details>
<summary>java.util.concurrent.CancellationException: Disconnected</summary>
	at reactor.core.publisher.FluxReplay$ReplaySubscriber.dispose(FluxReplay.java:1203)
	at reactor.core.publisher.FluxRefCount.cancel(FluxRefCount.java:102)
	at reactor.core.publisher.FluxRefCount$RefCountMonitor.innerCancelled(FluxRefCount.java:148)
	at reactor.core.publisher.FluxRefCount$RefCountInner.cancel(FluxRefCount.java:211)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.cancel(FluxFilterFuseable.java:190)
	at reactor.core.publisher.FluxTake$TakeFuseableSubscriber.cancel(FluxTake.java:444)
	at reactor.core.publisher.FluxTakeUntilOther$TakeUntilMainSubscriber.cancelOther(FluxTakeUntilOther.java:183)
	at reactor.core.publisher.FluxTakeUntilOther$TakeUntilMainSubscriber.cancel(FluxTakeUntilOther.java:191)
	at reactor.core.publisher.FluxTakeUntilOther$TakeUntilMainSubscriber.onError(FluxTakeUntilOther.java:220)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:135)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1505)
	at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:247)
	at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:329)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1505)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171)
	at reactor.core.publisher.FluxTake$TakeFuseableSubscriber.onComplete(FluxTake.java:424)
	at reactor.core.publisher.FluxTake$TakeFuseableSubscriber.onNext(FluxTake.java:404)
	at reactor.core.publisher.FluxRefCount$RefCountInner.onNext(FluxRefCount.java:188)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:810)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:894)
	at reactor.core.publisher.FluxReplay.subscribe(FluxReplay.java:1082)
	at reactor.core.publisher.FluxRefCount.subscribe(FluxRefCount.java:78)
	at reactor.core.publisher.FluxTakeFuseable.subscribe(FluxTakeFuseable.java:45)
	at reactor.core.publisher.MonoSingle.subscribe(MonoSingle.java:58)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3710)
	at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:128)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.MonoTakeUntilOther.subscribe(MonoTakeUntilOther.java:49)
	at reactor.core.publisher.MonoRepeatWhen.subscribe(MonoRepeatWhen.java:79)
	at reactor.core.publisher.MonoIgnoreElements.subscribe(MonoIgnoreElements.java:37)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3710)
	at reactor.core.publisher.FluxTakeUntilOther.subscribe(FluxTakeUntilOther.java:56)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7793)
	at reactor.core.publisher.Flux.subscribeWith(Flux.java:7957)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7786)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7750)
</details>

**Comment by simonbasle** [comment] 2021-01-28 14:47
This issue has been sitting unaddressed for quite some time, apologies.
I cannot reproduce the error with the latest version, but at the same time I had to adapt the snippets a bit.

None of these snippets make much sense to me though, they seem unnecessarily convoluted and the mental gap of having to translate them to Java for me to run them within the reactor testbase is certainly not helping.

I suspect the `CancelledException` make some amount of sense, as the reuse of `stream` and the multiple shares combined with fast-cancelling operators (`take(1)`, `single()`) cause the cancellation of the whole replay to happen at the same time the business error is emitted. We would need a more focused reproduction case to better investigate, ideally with some debug information (eg. is that trace traversing the first `takeUntilOther` or the second? ...)

Closing this as invalid/cannot-reproduce for the aforementioned reasons. If you still encounter that issue in the latest 3.3.x or 3.4.x versions, and can come up with a more focused reproduction case in Java and more data, please open a new issue.

**Closed by simonbasle** 2021-01-28 14:47 UTC
