### ISSUE TITLE
ParallelFlux / sequential does not keep initial order

### ISSUE THREAD

**Issue by adrilo** [reactor/reactor-core#2128] opened 2020-04-21 16:06 UTC
Using `.sequential()` on a ParallelFlux does not seem to keep the initial order of the elements in the Flux. The actual order is unfortunately not deterministic.

## Steps to Reproduce
```java
@Test
public void testSequential() {
    for (int i = 0; i < 1000; i++) {
        StepVerifier
            .create(
                Flux.just("a", "b", "c")
                    .parallel()
                    .runOn(Schedulers.parallel())
                    .map(String::toUpperCase)
                    .sequential()
            )
            .expectNext("A", "B", "C")
            .verifyComplete();
    }
}
```

## Your Environment
* Reactor version(s) used: 3.3.3.RELEASE & 3.3.4.RELEASE
* JVM version (`javar -version`): OpenJDK Runtime Environment Corretto-11.0.5.10.2

**Comment by simonbasle** [comment] 2020-04-22 17:18
Duplicate of #2130

**Closed by simonbasle** 2020-04-22 17:18 UTC
