### ISSUE TITLE
Add hashedTimer for Scheduler

### ISSUE THREAD

**Issue by hepin1989** [reactor/reactor-core#2965] opened 2022-03-14 05:01 UTC
Add hashedTimer for Scheduler, which will improve performance of large amount of timeouts.
![image](https://user-images.githubusercontent.com/501740/158107908-20cb7e08-b7d5-4c32-ab7f-25d6495bb0aa.png)
source:https://github.com/ifesdjeen/hashed-wheel-timer

**Comment by simonbasle** [comment] 2022-03-15 15:39
Seems related to https://github.com/reactor/reactor-core/issues/2845...
If not, please try to flesh out your feature request issues a bit more.

On a side note, we _absolutely_ cannot bring in code from the linked repository as it is using ESL, which requires code to be shared under the same license (and not our Apache 2 license).

**Comment by simonbasle** [comment] 2022-03-15 15:39
Duplicate of #2845

**Closed by simonbasle** 2022-03-15 15:39 UTC
Labels: status/duplicate
