### ISSUE TITLE
`Mono.fromCompletionStage` behaves differently from the documentation

### ISSUE THREAD

**Issue by benwiles1** [reactor/reactor-core#3235] opened 2022-10-17 20:50 UTC
## Documentation Issue
`Mono.fromCompletionStage` is documented to not cancel the future, but in pull request #3146 it was updated to do so. 

## Additional context
I was previously relying on the future not being cancelled, what is the recommended way to to get that behavior back?

**Comment by OlegDokuka** [comment] 2022-10-19 15:28
Looks like an indeed unexpected behavior change. Will roll it back and rework it to keep old expectations

**Comment by rstoyanchev** [comment] 2022-10-26 14:50
@benwiles1, could elaborate on your use case? Granted it is a regression, and that some control should be provided, it's not intuitive that cancel should not be passed on, and it would be useful to have a concrete scenario in mind.

**Comment by benwiles1** [comment] 2022-10-26 16:38
I was reusing the same `CompletableFuture` that was saved to a field and just wrapping it in a `Mono` on the fly as needed. I have realized that it probably makes more sense to instead just wrap the future into a mono once and `.cache()` it. (and it probably could be implemented from the ground up without using futures, I just haven't had the time to go back and improve it since getting more experience with this library)

I don't actually have a problem with the future being canceled, mostly just annoyed that the documentation wasn't updated.

**Comment by simonbasle** [comment] 2022-11-04 16:57
Fixed by #3272.

**Closed by simonbasle** 2022-11-04 16:57 UTC
Labels: type/documentation, warn/behavior-change
