### ISSUE TITLE
Ability to signal error upstream (nack) without cancelling/completing

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#73] opened 2016-04-26 14:19 UTC
Often when processing streams of messages from an external source there is a need to ack/nack the message.  When using a blocking API execution stack return implies you can ack and an exception being thrown (depending on type potentially) typically implies you need to nack.

When using using a reactive API it is much harder to determine when to ack/nack and I don't see any way in which the framework (reactor) helps with this, neither how I'd go about doing it myself really.  

Take this example:
`JMS.queue("in").map(msg -> processMsg(msg)).consume(System.out::println)`

If `processMsg` fails with an exception processing should not continue and the message should not be printed to the console, and at the same time this message should be nacked by the `JMS.queue` publisher.

Discussed a couple of options with @smaldini , but none of them ideal or even easily workable.. 

1. **Use Value<T> holder for success/error value**.  This approach isn't suitable because the next subscriber will be notified and this conflicts with the requirement above.

2. **Use `Exceptions.bubble(e)`.** This may work, but has a number of significant concerns:
 i) Throwing exceptions upstream like this is really reserved for fatal exceptions only
 ii) This approach requires the use of try/catch blocks and is not a programming model that is really compatible with everything else.
iii) What happens wen there are thread boundaries.
iv) https://github.com/reactor/reactor-core/issues/74

3. **Use a ErrorHandler within Message**
A more manual approach is to pass a ErrorHandler within the message being processed which is invoked on error. But this has it's own issues:
 i) If errors aren't thrown as exception then onNext() returning cannot be used to ack, so CompletionHandler is needed rather than ErrorHandler.
ii) How/when is onSucess() invoked? would need to add something non-transparent to the end of the stream to do this.
iii) How/when is onError() invoked? Can't just do it at the end of stream..

**Comment by akarnokd** [comment] 2016-04-26 14:36
How about JMS.queue() returns something that let's you communicate back an acknowledgement/rejection?

```java
JMS.queue("in").concatMap(manualMsg -> {
    try {
         Flux<R> result = Flux.just(processMessage(manualMsg));
         manualMsg.acknowledge();
         return result;
    } catch (Throwable ex) {
        manualMsg.reject();
        Exceptions.throwIfFatal();
        return Flux.error(ex);
    }
});
```

**Comment by dfeist** [comment] 2016-04-26 14:45
@akarnokd That's option 3).  *But* it's not quite so simple I don't think:

- You wouldn't want to do `Flux.error(ex)` as that is terminal. Not sure what you would return instead though?
- It's ok to nack/reject here, but IMO this is the wrong place to ack. Given you maybe have further processing steps which may fail. e.g. `JMS.queue("in").map(msg -> processMsg(msg)).map(msg -> convertMsg(msg)).consume(System.out::println). You only really want to ack at the end. You'd have to put a subscriber at the end to do it. 

This approach is doable, but ideally there be some spec/framework support for this, if it makes sense and is common.

**Comment by akarnokd** [comment] 2016-04-26 14:58
The problem is you have a per-value lifecycle and Reactive-Streams can't deal with it. The same issue appears with pooled ByteBuffers in I/O libraries where someone has to release the buffer once all stages have processed it and goes "out of scope".

The closest thing is what I call `umap` in Reactive-IO where you provide a transform for some upstream sequence and all participating object's lifecycle ends when the transformation terminates. In this context, you'd have:

```java
Flux<Void> JMS.queue(String topic, Function<Flux<Message>, Publisher<?>> umap);
```

(Note, however, that fatal exceptions break this too.)

**Comment by smaldini** [comment] 2016-04-26 15:28
That's the kind of pattern we try to implement from https://github.com/reactor/reactor-io/blob/master/reactor-ipc/src/main/java/reactor/io/ipc/Outbound.java#L44 where Netty (or Aeron) might receive a notification of failure. But implementing such contract in memory should be fairly easy.

**Comment by dfeist** [comment] 2016-04-26 19:38
While the approach for outbound IO in the example @smaldini provided makes sense and I can see how you would use that within a stream, I'm struggling to see how the 'umap' approach @akarnokd suggested  for this scenario could be used along with other operators in a stream. For example if you wanted to transform and then log each message using .map().consume(System.out::println), or is that not possible.

**Comment by smaldini** [comment] 2016-04-30 12:29
@dfeist should we consider the latest Mono#create addition enough for now and close this issue ?

**Comment by dfeist** [comment] 2016-05-01 10:06
@smaldini No, this is completely unrelated to Mono#create.  The solution to take a different approach to this scenario and not think of sources (at least one that need to know how stream terminates) not s Publishers, but as an something that create a stream and then is passed and applies a transformation to it.  (As explained by @akarnokd )

The only thing potentially outstanding here is the discussion we had with @sskrla around an alternative way to able to handle errors without i) requiring a Tuple everywhere, and having skip certain processing steps if error is present ii) causing a terminal error which requires re-subscription. This might be simply not possible though, given it conflicts with other things in the spec for a reason.

**Comment by dfeist** [comment] 2016-05-24 00:22
@smaldini We can close this out, this was an issue with the way i was attempting to use stream for request/response.

**Closed** 2016-05-24 01:10 UTC
Labels: question
