### ISSUE TITLE
How to test publisher with size and timeout buffer with StepVerifier?

### ISSUE THREAD

**Issue by chengchen** [reactor/reactor-core#464] opened 2017-03-05 19:32 UTC
Hello,

Recently, I start to use StepVerifier to test Flux and Monos in order to have less manual "waiting" during tests (also to speed up the tests). However, I am confused about how to make it work with bufferTimeout. I always have the similar issue with most of the processors:

**java.util.concurrent.RejectedExecutionException: Scheduler unavailable**

    @Test
    public void testWithoutBuffer_whichPasses() {
        final UnicastProcessor<String> processor = UnicastProcessor.create();

        final Publisher<Integer> publisher = processor.map(String::length);

        processor.onNext("foo");
        processor.onNext("foobar");

        StepVerifier.create(publisher)
            .expectSubscription()
            .expectNext(3)
            .expectNext(6)
            .thenCancel()
            .log().verify();
    }

    @Test
    public void testWithBuffer_whichDoesNotPass() {
        final UnicastProcessor<String> processor = UnicastProcessor.create();

        final Publisher<Integer> publisher = processor
            .bufferTimeout(5, Duration.ofSeconds(1))
            .map(words -> words.stream().map(String::length).collect(toList()))
            .flatMapIterable(Function.identity());

        processor.onNext("foo");
        processor.onNext("foobar");

        StepVerifier.withVirtualTime(() -> publisher)
            .expectSubscription()
            .thenAwait(Duration.ofSeconds(2))
            .expectNext(3)
            .expectNext(6)
            .thenCancel()
            .log().verify();
    }

The first test pass, however, the second one with buffer doesn't.. I am wondering what's the correct usage of the StepVerifier withVirtualTime?

Full example here:
https://github.com/chengchen/rx-smoker/blob/master/src/test/java/com/edgelab/marketdata/consumer/UnicastProcessorTest.java

Thank you very much for the help!

**Comment by simonbasle** [comment] 2017-03-09 14:08
there is a reason `StepVerifier` takes your `Flux` as a `Supplier`, and that is so that it can **defer its creation**. Otherwise, the flux will be instantiated using default schedulers that are not virtual-time enabled. Simply replace `publisher` in the lambda with the actual operator chain.

Note you can also do the `processor.onNext` from inside the StepVerifier's scenario like `then(() -> processor.onNext("third value arriving later"))`

**Comment by simonbasle** [comment] 2017-03-09 15:08
closing as duplicate of reactor/reactor-addons#85

**Closed by simonbasle** 2017-03-09 15:08 UTC
Labels: duplicate, question
