### ISSUE TITLE
Fix examples in 'Fallback Method' section

### ISSUE THREAD

**Issue by mshutov** [reactor/reactor-core#1323] opened 2018-08-21 09:28 UTC
"Fallback Method" section offers two examples and both of them expect that `k` variable is available inside callback passed to `onErrorResume` , but that isn't true.
Simple fix is to enclose them inside some function with `k` as parameter and use `Mono#just`. 
Also provided samples will work unexpectedly if we fail for the first key - we won't even try to obtain a value for the second key from any of the sources.

**Comment by simonbasle** [comment] 2018-08-21 12:37
This has already been reported and fixed in the maintenance branch, pending a 3.1.x release. You can see the current fixed snippets for the (yet unreleased) 3.1.9 [here](http://projectreactor.io/docs/core/3.1.9.BUILD-SNAPSHOT/reference/#error.handling).

**Comment by simonbasle** [comment] 2018-08-21 12:37
Duplicate of #1269

**Closed by simonbasle** 2018-08-21 12:37 UTC

**Comment by mshutov** [comment] 2018-08-21 12:40
@simonbasle Thank you. I've searched but failed to find that issue.
