### ISSUE TITLE
add Closeable interface , developer duplication define Closeable interface 

### ISSUE THREAD

**Issue by qinarmy-zoro** [reactor/reactor-core#3580] opened 2023-09-15 17:23 UTC
hope add Closeable interface ,because  developer duplication define Closeable interface 

## Desired solution

```java

public interface Closeable {

    <T> Mono<T> close();

    boolean isClosed();


}

```

**Comment by OlegDokuka** [comment] 2023-09-18 12:23
probably duplicate of #3173

**Closed** 2023-09-18 12:24 UTC
Labels: status/duplicate
