### ISSUE TITLE
Context is lost when invoking doFinally operators

### ISSUE THREAD

**Issue by Cesarla** [reactor/reactor-core#2591] opened 2021-02-04 09:40 UTC
## Expected Behavior

The context-view is present when invoking `doFinally`. It used to work on 3.3.5, but no longer does after upgrading to 3.4.

## Actual Behavior

The context-view is lost when invoking `doFinally`.

## Steps to Reproduce

Here is a test case for the missing context while invoking `doFinally` blocks, I am linking a gist with the [MdcContextLifter](https://gist.github.com/Cesarla/d58bc59f68aac5ed48ad79c70fef8997 ) code that I use to log the context-view as MDCs:
```java
@Test
void reproCase() {
        // given
        Hooks.onEachOperator(MdcContextLifter.class.getName(), Operators.lift((__, subscriber) -> new MdcContextLifter<>(subscriber)));
        var logs = Loggers.addListAppender(MdcContextLifterTest.class);

        // when
        Flux.empty()
            .doFinally(v -> {
                LOG.info("Lore Ipsum");
            })
            .contextWrite(Context.of("doFinally", "Test"))
            .subscribe();

        // then
        await().untilAsserted(() ->
            assertThat(logs.list.stream()).anyMatch(
                m -> m.getMDCPropertyMap().entrySet().containsAll(
                    Map.of("doFinally", "Test").entrySet()
                )));
}
```

## Your Environment

* Reactor version(s) used: 3.4.0 and 3.4.2 (was working ok on 3.3.5 and previous versions)
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
* OS and version (eg `uname -a`):

**Comment by simonbasle** [comment] 2021-02-04 15:41
I can indeed reproduce, without the log part which is missing some pieces from our perspective (repro case cannot be copy-pasted into a reactor-core unit test as-is).

This all seem to stem from the fact that in 3.3.x, the `onEachOperator` hook wasn't applied to `.subscriberContext(...)`, whereas in 3.4.x it now is.

It might have been an unintended change, as a side effect of the renaming effort around context write/read operators... That said, arguably, `contextWrite` IS an operator so it sounds like the right thing to do.

Would you be able to investigate further, knowing that, and see if the `MdcContextLifter` can be improved maybe?

**Comment by simonbasle** [comment] 2021-03-05 10:52
Closing this as we think the behavior of passing `contextWrite` to the `onEachOperatorHook` is the right thing to do. Let us know if you found a way to improve `MdcContextLifter` to account for that.

**Closed by simonbasle** 2021-03-05 10:52 UTC
Labels: status/need-decision

**Comment by Cesarla** [comment] 2021-03-06 11:57
Hi @simonbasle, I ended up "solving" the problem by filtering out contextWrite from onEachOperatorHook, without requiring any change on MdcContextLifter.
