### ISSUE TITLE
Threads not stopped on shutdown

### ISSUE THREAD

**Issue by KatieKoslosky** [reactor/reactor-core#3428] opened 2023-04-07 15:48 UTC
Since upgrading from Sprint Boot 2.5.6 to Spring Boot 2.7.9, I see numerous warning on application shutdown notifying me that threads have not been properly stopped. Through testing, I discovered this was related to the usage of Schedulers in reactor-core, and I produced a minimal code example

## Expected Behavior
I would expect to not receive a warning about threads being left open and a possible memory leak on application shutdown.

## Actual Behavior
Error messages on shutdown for each time the code that utilized Schedulers is called. 
```
2023-03-24 15:32:07.889 WARN 13988 --- [n(29)-127.0.0.1] o.a.c.loader.WebappClassLoaderBase : The web application [ROOT] appears to have started a thread named [parallel-2] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:750)
2023-03-24 15:32:07.890 WARN 13988 --- [n(29)-127.0.0.1] o.a.c.loader.WebappClassLoaderBase : The web application [ROOT] appears to have started a thread named [parallel-3] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:750)
2023-03-24 15:32:07.890 WARN 13988 --- [n(29)-127.0.0.1] o.a.c.loader.WebappClassLoaderBase : The web application [ROOT] appears to have started a thread named [parallel-4] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:750)
```

## Code to Reproduce
```java
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import reactor.core.publisher.Flux;
import reactor.core.scheduler.Schedulers;

@RestController
public class GreetingController {
   

	@GetMapping("/greeting")
	public Flux<Integer> greeting(@RequestParam(value = "name", defaultValue = "World") String name) {
		Flux<Integer> flux = Flux.range(0, 2)
                .publishOn(Schedulers.parallel());
		return flux;
	}
}
```
## Your Environment

dependencies from pom.xml:

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		
		<dependency>
		    <groupId>io.projectreactor</groupId>
		    <artifactId>reactor-core</artifactId>
		</dependency>
	</dependencies>

* Reactor version(s) used: 3.4.28
* JVM version (`java -version`): 1.8.0_333
* OS and version (eg `uname -a`): Windows

**Comment by OlegDokuka** [comment] 2023-04-10 14:45
Hi @KatieKoslosky!

Thank you for creating an issue.
To proceed we need an isolated test (ideally just the project reactor) which reproduces the issue.
Otherwise, it is hard to say something since we have tests proving all threads are shut down.

If you can not provide a reproducer, feel free to reopen that issue at spring-framework

**Comment by KatieKoslosky** [comment] 2023-04-14 13:38
Hi @OlegDokuka . I will try to create a reproducer that does not include spring boot today.

However, I think at a minimum I need to include Tomcat as Tomcat as what is detecting the un-closed threads. I don't think an example limited to reactor-core is capable of reproducing the issue.

**Comment by OlegDokuka** [comment] 2023-04-16 17:54
@KatieKoslosky there are number of tools ( e.g visualvm) which allows tracking active threads, thus we need an exact reproducer which clearly states that the problem is on the reactor side. Including external libraries unrelated and disconnected from the project expands the surface for research. That can increase the time team will spend to identify the problem. We have limited people capacity and we appreciate any effort to reduce the time we spend on investigations

**Comment by OlegDokuka** [comment] 2023-10-02 06:49
closing this one since no feedback was provided

**Closed** 2023-10-11 18:04 UTC
