### ISSUE TITLE
windowTimeout does not handle backpressure

### ISSUE THREAD

**Issue by yarosla** [reactor/reactor-core#1292] opened 2018-07-29 14:37 UTC
### Expected behavior

`windowTimeout` works with slow subscribers.

### Actual behavior

It throws overflow exception: "The receiver is overrun by more signals than expected".

### Steps to reproduce

`windowTimeout` always requests unbounded number of items. When subscriber requests limited number of items, it gets easily overflown. Here is the Spock spec that currently passes:

    def flux = Flux.range(1, 2)
                .windowTimeout(1, Duration.ofHours(1))
                .flatMap({ it }, 1, 1)
        def verifier = StepVerifier.create(flux, 1) // request(1)
                .expectNext(1)
                .expectErrorMatches({ it.message.contains 'The receiver is overrun by more signals than expected' })
        when:
        verifier.verify()
        then:
        notThrown(Exception)

### Question

Looking at the code it seems to be an intended behavior. What is best practice then to use `windowTimeout` with slow subscribers?

### Reactor Core version

3.1.8

### JVM version (e.g. `java -version`)

1.8.171

**Comment by OlegDokuka** [comment] 2018-07-29 15:07
Hey @yarosla. For now, `windowTimeout`/`bufferTimeout` has limitations and does not support backpressure at all. Possibly, in the nearest feature that will be changed and similar operators will be provided in place to solve that problem.

**Comment by yarosla** [comment] 2018-07-29 18:06
Thanks. It is clear now.

Perhaps this issue can be closed as a duplicate. Sorry for not finding that earlier one.

**Comment by simonbasle** [comment] 2018-07-30 07:54
Duplicate of #1099

Due to the nature of such timed operators, it is difficult to implement backpressure and the timeout should be set in accordance with the expected rate of consuming.

There might be a way to build an `interval` that respects backpressure, but I don't see this as easily adaptable to windowTimeout/bufferTimeout.

**Comment by simonbasle** [comment] 2018-07-30 07:55
Duplicate of #1099

**Closed by simonbasle** 2018-07-30 07:55 UTC
