### ISSUE TITLE
Thread-context propagation is missing after `contextWrite`

### ISSUE THREAD

**Issue by dstepanov** [reactor/reactor-core#3500] opened 2023-06-16 13:16 UTC
The problem occurs for mono and flux.
I think the problem is in `MonoContextWriteRestoringThreadLocals` and `FluxContextWriteRestoringThreadLocals`:

Newly modified context `c` is correctly passed to `ContextWriteRestoringThreadLocalsSubscriber`:
```java
public void subscribe(CoreSubscriber<? super T> actual) {
		Context c = doOnContext.apply(actual.currentContext());

		try (ContextSnapshot.Scope ignored = ContextPropagation.setThreadLocals(c)) {
			source.subscribe(new ContextWriteRestoringThreadLocalsSubscriber<>(actual, c));
		}
	}
```
but it's not used in the `setThreadLocals` calls:
```java
public void onSubscribe(Subscription s) {
			// This is needed, as the downstream can then switch threads,
			// continue the subscription using different primitives and omit this operator
			try (ContextSnapshot.Scope ignored =
					     ContextPropagation.setThreadLocals(actual.currentContext())) {
				if (Operators.validate(this.s, s)) {
					this.s = s;
					actual.onSubscribe(this);
				}
			}
		}
```

The problem can be reproduced in Micronaut PR by modifying this class https://github.com/micronaut-projects/micronaut-reactor/pull/306/files#diff-6bfb100b108ce8193896caf0431107f8a207233bd1545b7ac94e692a001ea901R38
To call `captureContext` just once:

```
                    interceptedMethod.handleResult(
                        captureContext(interceptedMethod.interceptResultAsPublisher(), propagatedContext)
                    );
```

2022.0.8

**Comment by OlegDokuka** [comment] 2023-06-19 07:54
@dstepanov contextWrite / contextCapture define a TL scope (all upstream operators) where TL context is available and guarantee that it is removed after (since all downstream operators do not have a reactor context hence the TL should not be available there as well).

we are happy to discuss existing guarantees if you have e a certain business use case where TL should be propagated downstream

**Comment by chemicL** [comment] 2023-06-19 10:21
The [Flux#contextCapture javadoc](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#contextCapture--) states the following:

> If [context-propagation library](https://github.com/micrometer-metrics/context-propagation) is on the classpath, this is a convenience shortcut to capture thread local values during the subscription phase and put them in the [Context](https://projectreactor.io/docs/core/release/api/reactor/util/context/Context.html) **that is visible upstream of this operator**

Choosing the appropriate Context to restore ThreadLocals from is important to be able to prevent leaking ThreadLocals to uncontrolled Threads where no cleanup can later be performed. When propagating signals upstream (subscribe/request/cancel) we choose the modified Context. When propagating signals downstream (onNext/onComplete/onError/onSubscribe) we use the Context from the downstream. This is aligned with the scope of the Context as per the javadoc.

If a use case for propagating context downstream, with the guarantee of cleaning up, is provided, we can consider that. I'm closing the issue for now. Please open a new one if you have an idea for such a functionality.

**Closed by chemicL** 2023-06-19 10:21 UTC
Labels: status/invalid, area/context

**Comment by dstepanov** [comment] 2023-06-19 13:26
I can simplify my example.

This is not working:
```groovy
        @MyTrace
        Flux<String> flux(String name) {
            PropagatedContext propagatedContext = PropagatedContext.get()
            return Mono.fromCallable {
                // This call requires correct thread-local propagated
                tracingInterceptor.getCurrectTrace().tag("fooFlux", "bar")
                return name
            }
            .flatMapMany { x -> Flux.just(x) }
            .subscribeOn(Schedulers.boundedElastic())
            .contextWrite(ctx -> ReactorPropagation.addPropagatedContext(ctx, propagatedContext))
        }
 ```

This is working by adding one no-op `contextWrite`:
```groovy
        @MyTrace
        Flux<String> flux(String name) {
            PropagatedContext propagatedContext = PropagatedContext.get()
            return Mono.fromCallable {
                // This call requires correct thread-local propagated
                tracingInterceptor.getCurrectTrace().tag("fooFlux", "bar")
                return name
            }
            .flatMapMany { x -> Flux.just(x) }
            .subscribeOn(Schedulers.boundedElastic())
            .contextWrite(ctx -> ctx) // Extra `contextWrite` fixes the propagation
            .contextWrite(ctx -> ReactorPropagation.addPropagatedContext(ctx, propagatedContext))
        }
 ```
`@MyTrace` is adding an interceptor that is modifying the thread-local. It doesn't do anything reactor-wise.

I'm not an expert on Reactor propagation, but this is clearly an issue.

**Comment by chemicL** [comment] 2023-06-20 14:04
We worked together with @dstepanov to create a reliable reproducer and discovered that the issue is with improperly handled scopes. The [recent change in context-propagation library (in 1.0.3)](https://github.com/micrometer-metrics/context-propagation/pull/103) allows reactor-core (from 3.5.7) to properly work with scoped scenarios. In order to properly propagate `ThreadLocal` state, a correct implementation of new API methods of `ThreadLocalAccessor` is required.
