### ISSUE TITLE
Overflow exception in windowTimeout

### ISSUE THREAD

**Issue by smiklos** [reactor/reactor-core#933] opened 2017-11-06 08:13 UTC
### Expected behavior
The stream completes without errors
### Actual behavior
An overflow exception is being thrown
### Steps to reproduce
Run the following code
```java
Flux.range(0, 1000)
    .map(Object::toString)
    .windowTimeout(10, Duration.ofMillis(50))
    .concatMap(window -> window.reduce("", (s, s2) -> s + s2)
                               .subscribeOn(Schedulers.elastic()))
    .blockLast();
```
### Reactor Core version
3.1.1.Final
### JVM version (e.g. `java -version`)
1.8.0_151-b12
### OS version (e.g. `uname -a`)
Ubuntu 16.04

**Comment by OlegDokuka** [comment] 2017-11-06 10:49
Investigating. Seems that request from concatMap does not adjusted in window operator

**Comment by OlegDokuka** [comment] 2017-11-06 15:01
After some investigation was found that the issue is caused by the fact that `windowTimeout` operator push elements much faster than downstream subscription may consume it. Since the subscription take a place on the separate Thread (`.subscribeOn(...)`), the creation of new Thread and execution `.subscribe` and subsequent `.onSubscribe` (and of course subsequent `request(...)` execution) methods may take much more time than upstreams emitting window. Thus, I'm not sure that it is a fixable problem for now.

Also, the elimination of `.subscribeOn` fixes the problem.

The problem may be fixed by introducing some `onBackpressureXXX` operator between `windowTimeout` and `concateMap`

**Comment by simonbasle** [comment] 2017-11-06 16:47
(closing as `wontfix` as this is more of a pipeline characteristic issue than a bug, thanks for investigating @OlegDokuka)

**Closed** 2017-11-06 16:47 UTC
Labels: wontfix
