### ISSUE TITLE
MonoRetryWhen Behaviour: Retry onError despite onNext has happened

### ISSUE THREAD

**Issue by OlegDokuka** [reactor/reactor-core#2078] opened 2020-03-18 23:54 UTC
Interesting observation. 
`MonoRetryWhen` retry error even onNext has already happened.

Do we want to MonoRetryXXX behave in such a way?

**Comment by simonbasle** [comment] 2020-03-24 10:53
It should probably not. That said, strictly speaking the `Mono` contract disallows `onNext + onError`. Can you share an example that lead to that situation?

**Comment by OlegDokuka** [comment] 2020-03-24 11:23
Yup.

```java
public static void main(String[] args) throws InterruptedException {

	TestPublisher testPublisher = TestPublisher.create();
	Mono.fromDirect(testPublisher)
		.retryWhen(Retry.fixedDelay(3, Duration.ofMillis(10)))
		.subscribe(new BaseSubscriber() {
			@Override
			protected void hookOnNext(Object value) {
				System.out.println("Next " + value);
			}

			@Override
			protected void hookOnComplete() {
				System.out.println("Done");
			}

			@Override
			protected void hookOnError(Throwable throwable) {
				System.out.println("Error " + throwable);
			}

			@Override
			protected void hookFinally(SignalType type) {
				System.out.println("Finally " + type);
			}
		});

	testPublisher.next(1);
	testPublisher.error(new RuntimeException("test"));

	Thread.sleep(1000);

}
```

Giving the output 

```
Next 1
Error reactor.core.Exceptions$RetryExhaustedException: Retries exhausted: 3/3
Finally onError
```

In general, this is a pretty rare case, because in many places we do `MonoOperator`, but just in case one decided to use it with `Mono.fromDerict` and a `Publisher` which can emit `onNext` + `onError`, then behavior can be unexpected (because we use `retryWhen` impl from `Flux`).

I would suggest marking is as minor but to rework it in case we have no other prioritized task in the backlog

**Comment by simonbasle** [comment] 2020-03-24 11:34
I would argue that `fromDirect` with an invalid `Publisher` that doesn't conforms to the `Mono` contract` is a mistake, and the result is undeterministic at that point, isn't it? The case for `fromDirect` is rare, `from(Publisher)` is more strict.

**Comment by OlegDokuka** [comment] 2020-03-24 11:41
And yes and nope. `Mono` guarantees to deliver a single value + terminal signal or terminal signal. 

So I would debate whether onNext + onError is an invalid behavior.
But I have to agree that we do not have any samples where we can have onNext + onError so that should be invalid.

Do we have anywhere in the docs specified that onNext + onError is invalid?

**Comment by simonbasle** [comment] 2020-03-24 14:56
This has come up in the past. Since `Mono` is not part of the rs spec it
seems that contract is not defined clearly enough, the javadoc leaving too
much room for interpretation:
A Reactive Streams Publisher (...) that completes successfully by emitting
an element, or with an error.

Looking at sources it is clearly enforced, though, and another
manifestation of that contract is that all of core mono implementations
directly call `onComplete` upon propagating `onNext`, or that Mono.from
subscriber will enforce that contract.
We should definitely make that more prominent in the docs.

**Comment by simonbasle** [comment] 2020-11-06 14:44
closing this, superseded by #2481

**Closed by simonbasle** 2020-11-06 14:44 UTC
Labels: for/user-attention

**Comment by kitkars** [comment] 2023-12-15 14:12
@simonbasle 
Apologies to raise in the closed ticket. I do understand I could use `Mono.from`. But `Mono.fromDirect` should NOT surprise the user. Mono is supposed to emit 1 item. 
```
Flux<Integer> flux = Flux.just(1, 2, 3, 4);
Mono.fromDirect(flux)
	.doOnNext(System.out::println) // prints 1, 2, 3, 4
	.block();
```
Is this not a bug?

**Comment by chemicL** [comment] 2023-12-15 14:47
@kitkars from the javadoc of `fromDirect`:

```
	 * Convert a {@link Publisher} to a {@link Mono} without any cardinality check
	 * (ie this method doesn't cancel the source past the first element).
	 * Conversion transparently returns {@link Mono} sources without wrapping and otherwise
	 * supports {@link Fuseable} sources.
	 * Note this is an advanced interoperability operator that implies you know the
	 * {@link Publisher} you are converting follows the {@link Mono} semantics and only
	 * ever emits one element.
```

My POV: no, not a bug.

**Comment by kitkars** [comment] 2023-12-15 15:23
@chemicL I did see that. Thanks. Hate to continue the conversation here. But can you tell one use case where it will be useful and we can not achieve that `Flux.from`.
If we expose a method saying it is Mono and it can emit more than 1, it violates the contract. 
If we are NOT sure of the publisher, people should be encouraged to use` Flux.from` to be safe.

```
	public Mono<Integer> test(){
		Flux<Integer> flux = Flux.just(1, 2, 3, 4);
		return Mono.fromDirect(flux)
			.doOnNext(System.out::println);
	}
```

**Comment by chemicL** [comment] 2023-12-15 16:07
It is an optimization manouver, which allows to skip enforcing the contract when the user knows that something else is already enforcing it. Feel free to simply checkout the reactor-core repository and find the usages of `Mono.fromDirect` using your IDE, I'm certain it will become more apparent after such an exercise.
