### ISSUE TITLE
reactor.core.Exceptions$ErrorCallbackNotImplemented: reactor.core.Exceptions$OverflowException: Could not emit buffer due to lack of requests

### ISSUE THREAD

**Issue by patpatpat123** [reactor/reactor-core#3416] opened 2023-03-24 22:42 UTC
Hello Team,

I am encountering this issue reproducible 100% with this snippet:

```
reactor.core.Exceptions$ErrorCallbackNotImplemented: reactor.core.Exceptions$OverflowException: Could not emit buffer due to lack of requests
Caused by: reactor.core.Exceptions$OverflowException: Could not emit buffer due to lack of requests
	at reactor.core.Exceptions.failWithOverflow(Exceptions.java:249)
	at reactor.core.publisher.FluxBufferTimeout$BufferTimeoutSubscriber.flushCallback(FluxBufferTimeout.java:227)
	at reactor.core.publisher.FluxBufferTimeout$BufferTimeoutSubscriber.lambda$new$0(FluxBufferTimeout.java:158)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

```
public Flux<Foo> issue() {
        Sinks.Many<Log> sink = Sinks.many().unicast().onBackpressureBuffer();
        kafkaReceiver.receive()
                .map(message -> convertMesageToFoo(message)
                )
                .bufferTimeout(Integer.MAX_VALUE, Duration.ofMillis(500))//tried many values for maxSize and maxTime
                .subscribe(new Subscriber<>() {
                    private Subscription subscription;
                    volatile boolean upstreamComplete = false;

                    @Override
                    public void onSubscribe(Subscription subscription) {
                        this.subscription = subscription;
                        subscription.request(1);
                    }

                    @Override
                    public void onNext(List<Foo> foos) {
                        reactiveElasticRepository.saveAll(foos)
                                .map(sink::tryEmitNext)
                                .doOnComplete(() -> {
                                    if (!upstreamComplete) {
                                        subscription.request(1);
                                    } else {
                                        sink.tryEmitComplete();
                                    }
                                })
                                .subscribe();
                    }

                    @Override
                    public void onError(Throwable throwable) {
                        throwable.printStackTrace();
                        System.err.println("I am able to reproduce this issue 100% " + throwable.getLocalizedMessage());
                        subscription.cancel();
                        sink.tryEmitError(throwable);
                    }

                    @Override
                    public void onComplete() {
                        upstreamComplete = true;
                    }
                });

        return sink.asFlux();
    }
```

May I ask if you could advise a workaround, or how this could be fixed please?

Thanks in advanced and good day.

**Comment by OlegDokuka** [comment] 2023-03-27 07:10
duplicate of #2236

**Closed** 2023-03-27 07:11 UTC
Labels: status/duplicate

**Comment by patpatpat123** [comment] 2023-03-27 07:32
Apologies for the duplicate.

May I just ask if there is a way to workaround this?

This seems to be a year-old issue.

(this is really just a question, not rushing anyone here)
