### ISSUE TITLE
MDC propagation when switching threads due to retryWhen(backoff)

### ISSUE THREAD

**Issue by Zozue** [reactor/reactor-core#2751] opened 2021-08-03 15:12 UTC
I am currently working with a WebClient and propagating MDC values using an ExchangeFilterFunction into the response thread.

```
    protected ExchangeFilterFunction propagateContextMap = (ClientRequest clientRequest, ExchangeFunction next) -> {
        Map<String, String> mdcMap = MDC.getCopyOfContextMap();
        return next.exchange(clientRequest)
                .doOnNext(value -> {
                    if (mdcMap != null)
                        MDC.setContextMap(mdcMap);
                });
    };
```

Using values a webclient function like below
```
    private Mono<JsonNode> getEntity(String uri, String bncId) {
        String authorizationValue = buildOktaTokenString();
        return webClient
                .get()
                .uri(uriBuilder -> uriBuilder.path(uri).build(entId))
                .header(AUTHORIZATION, authorizationValue)
                .exchange()
                .flatMap(this::handleResponse)
//                .retry(numRetries);
                .retryWhen(Retry.backoff(numRetries, Duration.ofMillis(100)));
    }
```

When using .retry, propagateContextMap is run again for each retry thread, but if I use retryWhen, it is never rerun.
While debugging, it seems that the exchange function is called at MonoRetry.java:50 `parent.resubscribe();`

Is this the expected behavior?

**Comment by simonbasle** [comment] 2021-08-09 08:33
That is strange. The `retryWhen` would also ultimately resubscribe to the source, so I see no reason the behavior would be different. Can you confirm this [line (`FluxRetryWhen#resubscribe`)](https://github.com/reactor/reactor-core/blob/5858505e7707f1ea1b75e1ad1b1002aadb8343b7/reactor-core/src/main/java/reactor/core/publisher/FluxRetryWhen.java#L216) is never hit during debugging?

Can you also share how you set up your `ExchangeFilterFunction`?

**Comment by simonbasle** [comment] 2021-08-09 09:33
After locally testing various configurations, I fail to reproduce a difference between `retry` and `retryWhen`.

But I think the issue is with your usage of `exchange()` (which is deprecated by the way). Unlike `retrieve()`, `exchange()` won't interpret any part of the response and won't propagate an `onError` with 500 responses from distant host.

This also heavily depends on what your `handleResponse` does, so please provide additional context here.

Also put a `log("retry")` before `retry[When]` and provide the logs (or log extracts) to show what the operator sees.

**Comment by simonbasle** [comment] 2021-08-11 09:15
ah, an MDC issue. your original description didn't make it very clear, instead more or less saying that `retry` and `retryWhen` seemed to have different re-subscription behavior. now I understand better.

I think the key difference between `retry` and `retryWhen` **with a backoff** here is that the later switches threads for the purpose of backing off by a `Duration`. As you've seen, execution continues on the `Schedulers.parallel()` scheduler.

I don't know if `ExchangeFilterFunction` can help you with that. If you add a `.publishOn(Schedulers.parallel())` right before `.retry()` in the first approach, does it still work?

But overall, setting MDC values / ThreadLocal on the netty threads is probably a huge footgun: the same thread can and will be interleaving processing for multiple requests. Same for the majority of `Scheduler`s (since limiting the number of threads in an application is one of the goals of Reactive Programming, most schedulers process a lot of flux/mono steps on the same thread(s) as asynchronous non-blocking interleaved pieces).

**Comment by Zozue** [comment] 2021-08-11 21:16
Sorry about that, I'm a bit new to some of this, so I'm learning as I go.

Using `.publishOn(Schedulers.parallel()).retry(3)` behaves in the same way as `retryWhen()` i.e. the MDC is not passed along.

#### `.publishOn(Schedulers.parallel()).retry(3)`
```
1; 20210811084721.000187AD; events-listener; [Test worker] c.n.r.e.service.Service ; cacc358d-9818-4eb1-bd7f-97f93c6bffc1; INFO;  >>> Retrieve entity
1; 20210811084721.000256AD; events-listener; [Test worker] c.n.r.e.config.OktaWebClientConfig ; cacc358d-9818-4eb1-bd7f-97f93c6bffc1; INFO; OktaClient-01: POST http://localhost:8089
1; 20210811084721.000417AD; events-listener; [reactor-http-nio-3] c.n.r.e.config.OktaWebClientConfig ; cacc358d-9818-4eb1-bd7f-97f93c6bffc1; INFO; OktaClient-02: 200 OK
1; 20210811084721.000449AD; events-listener; [Test worker] c.n.r.e.config.WebClientConfig ; cacc358d-9818-4eb1-bd7f-97f93c6bffc1; INFO; CLIENT-01 - GET http://localhost:8089/entity-api/BF863476FA2C0DEE39F4B0471DAB91A33E3036F3E111DFAD18773AE202982AD6
1; 20210811084721.000467AD; events-listener; [reactor-http-nio-3] c.n.r.e.provider.Client ; cacc358d-9818-4eb1-bd7f-97f93c6bffc1; INFO; retry
; 20210811084721.000469AD; ; [parallel-1] c.n.r.e.config.WebClientConfig ; ; INFO; CLIENT-01 - GET http://localhost:8089/entity-api/BF863476FA2C0DEE39F4B0471DAB91A33E3036F3E111DFAD18773AE202982AD6
1; 20210811084721.000476AD; events-listener; [reactor-http-nio-3] c.n.r.e.provider.Client ; cacc358d-9818-4eb1-bd7f-97f93c6bffc1; INFO; retry
; 20210811084721.000477AD; ; [parallel-2] c.n.r.e.config.WebClientConfig ; ; INFO; CLIENT-01 - GET http://localhost:8089/entity-api/BF863476FA2C0DEE39F4B0471DAB91A33E3036F3E111DFAD18773AE202982AD6
1; 20210811084721.000483AD; events-listener; [reactor-http-nio-3] c.n.r.e.provider.Client ; cacc358d-9818-4eb1-bd7f-97f93c6bffc1; INFO; retry
1; 20210811084721.000489AD; events-listener; [Test worker] c.n.r.e.listener.JMSListener ; cacc358d-9818-4eb1-bd7f-97f93c6bffc1; ERROR; !!!!! error processing message 
```

So it seems that this has more to do with the `Schedulers`... At least that's good to know.
Checking everything again, debugging shows that the `ExchangeFilterFunction` for each retry, so maybe I had just confused myself.

Would you have any suggestions on where to move forward? 

Right now, it seems that, if I really need to have this kind of value logged, I might need to avoid using `retryWhen` and manually rerun the `get()`.

**Comment by simonbasle** [comment] 2021-08-12 09:50
MDC is unreliable in a multi-threaded environment where one thread can serve multiple requests at the same time, because it relies on `ThreadLocal` and assumes 1 thread == 1 unit of processing (like a request).

That is why the `Context` was introduced in Reactor, in order to store contextual data tied to a `Flux`'s `Subscription` rather than shared thread(s). (and in WebFlux, a _request_ to a controller is indeed equivalent to a `Subscription` to that controller's `Flux`/`Mono`).


You can however manually populate the MDC (and clear it afterwards) at the points where you want to log messages with contextual information.

Have a look at the [reference guide FAQ entry for MDC](https://projectreactor.io/docs/core/release/reference/#faq.mdc) for some indication of how to do that (and make sure to read up on the [`Context`](https://projectreactor.io/docs/core/release/reference/#context) part too).

**Closed by simonbasle** 2021-08-12 09:50 UTC
Labels: for/user-attention, status/cannot-reproduce, for/other-project
