### ISSUE TITLE
Hooks caused error when use block()

### ISSUE THREAD

**Issue by will-zdu** [reactor/reactor-core#3458] opened 2023-05-10 01:28 UTC
## Expected Behavior

No error found
## Actual Behavior

found error 
Caused by: java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread single-1
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83)
	at reactor.core.publisher.Mono.block(Mono.java:1707)
	at com.example.examplereactor.TestHook1.lambda$main$0(TestHook1.java:46)
	at reactor.core.publisher.FluxStream.subscribe(FluxStream.java:48)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
## Steps to Reproduce

```java
package com.example.examplereactor;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import reactor.core.CoreSubscriber;
import reactor.core.Scannable;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Hooks;
import reactor.core.publisher.Mono;
import reactor.core.publisher.Operators;
import reactor.core.scheduler.Schedulers;

import java.util.Arrays;
import java.util.List;
import java.util.function.BiFunction;
import java.util.stream.Stream;

public class TestHook1 {

    private static final Logger logger = LoggerFactory.getLogger(TestHook1.class);

    static {
        try {
            Hooks.onEachOperator("testHook", Operators.lift(new Lifter<>()));
        } catch (Throwable ignored) {
        }
    }


    public static class Lifter<T>
            implements BiFunction<Scannable, CoreSubscriber<? super T>, CoreSubscriber<? super T>> {

        /**
         * Holds reference to strategy to prevent it from being collected.
         */

        @Override
        public CoreSubscriber<? super T> apply(Scannable publisher, CoreSubscriber<? super T> sub) {
            return sub;
        }
    }
    public static void main(String[] args) throws InterruptedException {

        Flux.fromStream(() -> {
            logger.info("Operation fromStream enter call1: ");
            Mono.just("test1").block();
            return  Stream.of(
                    "scene 1",
                    "scene 2",
                    "scene 3",
                    "scene 4",
                    "scene 5"
            );
        }).publishOn(Schedulers.boundedElastic()).subscribeOn(Schedulers.single()).subscribe();

        Thread.sleep(3000);
    }
}

```

## Your Environment

* Reactor version(s) used:  3.4.24
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): JDK 11 ,JDK17 both will reproduce it
* OS and version (eg `uname -a`): Linux core 5.4.0-144-generic

**Comment by will-zdu** [comment] 2023-05-10 01:40
link to https://github.com/reactor/reactor-core/issues/3452 https://github.com/reactor/reactor-core/issues/3450
looks similar to this https://github.com/reactor/reactor-core/issues/3450,but not all the same,https://github.com/reactor/reactor-core/issues/3450 caused execute on different thread,but this bug caused Mono.just() -> reactor.core.publisher.MonoOnAssembly,the block() method will execute reactor.core.publisher.Mono#block(),it will be report an error,without hooks,Mono.just()  will return reactor.core.publisher.MonoCallableOnAssembly,the block() method on MonoCallableOnAssembly will not do check about thread is NonBlocking or not

**Comment by OlegDokuka** [comment] 2023-05-19 08:34
duplicate of #3450

**Closed by OlegDokuka** 2023-05-19 08:34 UTC
Labels: :question:need-triage

**Comment by will-zdu** [comment] 2023-05-19 08:41
@OlegDokuka  Please review my suggestion. If this problem is not resolved, the observability of the reactor cannot be achieved, and this problem is too dangerous. If it cannot be solved, can we try to abandon hooks?

**Comment by OlegDokuka** [comment] 2023-05-19 16:27
@will-zdu you have an option to filter operators, that say you may choose which to affect and which should be skip. 

Apart from that, I dont expect observability affects threading, I expect it just intercepts specific part of the logic. 
The code, given in the original post, is semantically incorrect since you expect `publishOn` to work as `subscribeOn`. 

if you want to have values generated on boundedElasitc, the code should be edited as follows: 

```java
public class TestHook1 {

    private static final Logger logger = LoggerFactory.getLogger(TestHook1.class);

    static {
        try {
            Hooks.onEachOperator("testHook", Operators.lift(new Lifter<>()));
        } catch (Throwable ignored) {
        }
    }


    public static class Lifter<T>
            implements BiFunction<Scannable, CoreSubscriber<? super T>, CoreSubscriber<? super T>> {

        /**
         * Holds reference to strategy to prevent it from being collected.
         */

        @Override
        public CoreSubscriber<? super T> apply(Scannable publisher, CoreSubscriber<? super T> sub) {
            return sub;
        }
    }
    public static void main(String[] args) throws InterruptedException {

        Flux.fromStream(() -> {
            logger.info("Operation fromStream enter call1: ");
            Mono.just("test1").block();
            return  Stream.of(
                    "scene 1",
                    "scene 2",
                    "scene 3",
                    "scene 4",
                    "scene 5"
            );
        }).subscribeOn(Schedulers.boundedElastic()).publishOn(Schedulers.boundedElastic()).subscribeOn(Schedulers.single()).subscribe();

        Thread.sleep(3000);
    }
}
```

In all other cases you abuses "feature" behaviour of `publishOn` and we dont give any guarantee that this behavuiour will be consistent in all the cases
