### ISSUE TITLE
OSGI is not able to deploy io.projectreactor with lettuce 6.0.2

### ISSUE THREAD

**Issue by jigneshmpatel** [reactor/reactor-core#2620] opened 2021-02-21 02:57 UTC
I am trying to use lettuce 6.0.2 with OSGI and wildfly. lettuce -core has dependencies on io.projectreactor. So I have created following dependencies.
```
        <dependency>
            <groupId>io.lettuce</groupId>
            <artifactId>lettuce-core</artifactId>
            <version>6.0.2.RELEASE</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-pool2</artifactId>
            <version>2.9.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-common</artifactId>
            <version>4.1.59.Final</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-handler</artifactId>
            <version>4.1.59.Final</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport</artifactId>
            <version>4.1.59.Final</version>
           <scope>compile</scope>
        </dependency>

 <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>3.3.14.RELEASE</version>
           <scope>compile</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.reactivestreams</groupId>
            <artifactId>reactive-streams</artifactId>
            <version>1.0.3</version>
           <scope>compile</scope>
            <optional>true</optional>
        </dependency>

         <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <version>3.2.0</version>
                <extensions>true</extensions>
                <configuration>
                    <instructions>
                        <Bundle-SymbolicName>${project.groupId}.${project.artifactId}</Bundle-SymbolicName>
                        <Bundle-Version>1.0.0</Bundle-Version>
                        <Bundle-Activator>com.elasticache.Activator</Bundle-Activator>
                        <Bundle-Vendor>xxxxxxx</Bundle-Vendor>
                        <Bundle-Category>osgi</Bundle-Category>
                        <Export-Package>
                            <--!  internal packages -->
                        </Export-Package>
                        <Import-Package>
                            org.slf4j;version="1.7.7",javax.net.ssl,javax.security.cert
                        </Import-Package>
                       <!-- <Embed-Dependency>lettuce-core,commons-pool2,netty-transport,netty-common,netty-handler,reactor-core,org.reactivestreams</Embed-Dependency>-->
                        <!--<Embed-Dependency>lettuce-core,commons-pool2,netty-transport,netty-common,netty-handler,reactor-core,org.reactivestreams</Embed-Dependency>-->
                        <Embed-Dependency>lettuce-core,commons-pool2,netty-transport,netty-common,netty-handler,reactor-core,org.reactivestream</Embed-Dependency>

                        <Embed-Transitive>true</Embed-Transitive>
                        <!--<Embed-Dependency>lettuce-core,commons-pool2,netty-common,netty-handler,netty-transport,reactor-core</Embed-Dependency>-->
                    </instructions>
                </configuration>
            </plugin>
```

I am using JDK 1.8.
## Expected Behavior
The system should deploy the OSGI bundle to wildfly 10.
## Actual Behavior
System gives following error:
```
ERROR [com.icare.elasticacheclient] (Thread-91) [MSC service thread 1-7] Invocation of 'init' failed.: java.lang.NoClassDefFoundError: Failed to link reactor/core/publisher/DirectProcessor (Module "deployment.elasticacheclient-1.0.0.jar:main" from Service Module Loader): Failed to link reactor/core/publisher/FluxProcessor (Module "deployment.elasticacheclient-1.0.0.jar:main" from Service Module Loader): org/reactivestreams/Processor
	at sun.reflect.GeneratedConstructorAccessor44.newInstance(Unknown Source) [:1.8.0_275]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.8.0_275]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [rt.jar:1.8.0_275]
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:446) [jboss-modules.jar:1.5.2.Final]
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:274) [jboss-modules.jar:1.5.2.Final]
	at org.jboss.osgi.framework.internal.HostBundleClassLoader.loadClassLocal(HostBundleClassLoader.java:73) [jbosgi-framework-core-5.0.1.Final.jar:5.0.1.Final]
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:78) [jboss-modules.jar:1.5.2.Final]
	at org.jboss.modules.FilteredIterableLocalLoader.loadClassLocal(FilteredIterableLocalLoader.java:44) [jboss-modules.jar:1.5.2.Final]
	at org.jboss.modules.Module.loadModuleClass(Module.java:606) [jboss-modules.jar:1.5.2.Final]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190) [jboss-modules.jar:1.5.2.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363) [jboss-modules.jar:1.5.2.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351) [jboss-modules.jar:1.5.2.Final]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93) [jboss-modules.jar:1.5.2.Final]
	at io.lettuce.core.event.DefaultEventBus.<init>(DefaultEventBus.java:38)
	at io.lettuce.core.resource.DefaultClientResources.<init>(DefaultClientResources.java:186)
	at io.lettuce.core.resource.DefaultClientResources$Builder.build(DefaultClientResources.java:567)
	at io.lettuce.core.resource.DefaultClientResources.create(DefaultClientResources.java:247)
	at io.lettuce.core.AbstractRedisClient.<init>(AbstractRedisClient.java:102)

```
## Steps to Reproduce

```java
@Test
void reproCase() {

}
```

## Your Environment

* Reactor version(s) used:3.3.14
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`1.8`):
* OS and version (big-sur):

**Comment by simonbasle** [comment] 2021-02-22 14:23
Reactor 3.3.14.RELEASE and Lettuce Core 6.0.2.RELEASE should be compatible, the former declares a dependency to reactor-core 3.3.13.RELEASE but `DirectProcessor` certainly hasn't disappeared between these two releases...

I have no idea what the `felix` plugin is doing, are you 100% sure there isn't a misconfiguration there?

**Comment by simonbasle** [comment] 2021-03-02 17:12
@jigneshmpatel have you been able to investigate and pin-point the root cause?

I'm closing this as I don't think the root cause is in reactor's OSGI configuration.
If you find the root cause to really be in reactor-core, feel free to further comment with suggestions on how to fix and we'll re-open this.

**Closed by simonbasle** 2021-03-02 17:12 UTC
Labels: for/user-attention, status/declined
