### ISSUE TITLE
Reactor Kafka throws error ( Could not create new window due to lack of requests )

### ISSUE THREAD

**Issue by jainvi077** [reactor/reactor-core#3463] opened 2023-05-16 15:57 UTC
We are using reactor kafka to consume messages from a kafka topic and we are also using reactor Flux's windowing feature to batch together records for certain duration as shown below.

** kafkaFlux = kafkaFlux .window( Duration.ofSeconds((Long) config.getAdditionalProps().get(WINDOWING_TIMESPAN))) .flatMap(....).**

But Occasionally we receives below errors and our kafka consumer stop consuming messages after this error.

reactor.core.Exceptions$ErrorCallbackNotImplemented: reactor.core.Exceptions$OverflowException: Could not create new window due to lack of requests Caused by: reactor.core.Exceptions$OverflowException: Could not create new window due to lack of requests at reactor.core.Exceptions.failWithOverflow(Exceptions.java:237) at reactor.core.publisher.FluxWindowBoundary$WindowBoundaryMain.drain(FluxWindowBoundary.java:346) at reactor.core.publisher.FluxWindowBoundary$WindowBoundaryMain.boundaryNext(FluxWindowBoundary.java:259) at reactor.core.publisher.FluxWindowBoundary$WindowBoundaryOther.onNext(FluxWindowBoundary.java:414) at reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:125) at reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59) at reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829)

Any help with the root cause of the error would very helpful. Thank You.

We expect to see our kafka consumer consuming messages without any error.

**Comment by OlegDokuka** [comment] 2023-05-19 08:52
duplicate of #3106. 

To workaround that, I recommend to use `windowTimeout(Integer.MAX_VALUE, Duration, fairBackpressure=true)` as of now

**Closed by OlegDokuka** 2023-05-19 08:52 UTC
Labels: status/duplicate
