### ISSUE TITLE
Mono.fromRunnable(...) never emits where Mono.fromCallable(...) does

### ISSUE THREAD

**Issue by Jamalarm** [reactor/reactor-core#455] opened 2017-03-02 15:23 UTC
We encountered what seems like a bug (could be wrong!)

We have found that this code works (all events are asynchonously passed to `processEvent`):
```
replayEventsStream
            .flatMap(event -> Mono.fromCallable(() -> {
                pipelines.get(event.getQueueId()).processEvent(event);
                return event;
            }).subscribeOn(Schedulers.elastic()), concurrency)
            .doOnComplete(completionHook::countDown)
            .doOnError((e) -> completionHook.countDown())
            .subscribe();
```
while this code will complete immediately with no events processed via processEvent
```
replayEventsStream
            .flatMap(event -> Mono.fromRunnable(() -> {
                pipelines.get(event.getQueueId()).processEvent(event);
            }).subscribeOn(Schedulers.elastic()), concurrency)
            .doOnComplete(completionHook::countDown)
            .doOnError((e) -> completionHook.countDown())
            .subscribe();
```

The only difference is `fromCallable()` vs `fromRunnable()`. Any ideas?

**Comment by akarnokd** [comment] 2017-03-02 15:47
Barebone unit test:

```java
@Test
    public void test() {
        int c[] = { 0 };
        Flux.range(1, 1000)
        .flatMap(v -> Mono.fromRunnable(() -> { c[0]++; }))
        .ignoreElements()
        .block();
        
        Assert.assertEquals(1000, c[0]);
    }
```

**Comment by smaldini** [comment] 2017-03-02 15:56
Hey thanks for the report, please use hide() in front of fromRunnable() as a workaround is indeed a bug that will be fixed in a sec.

**Closed** 2017-03-02 15:59 UTC
Labels: bug

**Comment by yu199195** [comment] 2018-09-03 03:46
ues hide ？

**Comment by yu199195** [comment] 2018-09-03 03:48
now i use  Mono.fromRunnable()     ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped by webflux-http

**Comment by AhmedGoudaa** [comment] 2019-08-25 19:42
Still can't do  using `V3.2.11.RELEASE `
```
Mono<String> fromCallable =
 Mono.fromRunnable(() -> {
      System.out.println("fromCallable ");
    }).map(anyVal -> {
      System.out.println(" in mapping Mapping ");
      return "any";
    });

    fromCallable_.subscribe();

```
prints "fromCallable" only .
any help ?

**Comment by jasiekpor** [comment] 2023-01-12 12:48
```
Mono.fromRunnable(() -> {
      System.out.println("fromCallable ");
    })
```
this emits no elements, so the map operation will not be executed (no object to be mapped). This is by design.

**Comment by jasiekpor** [comment] 2023-01-12 12:49
> Still can't do maping using `V3.2.11.RELEASE `
> 
> ```
> Mono<String> fromCallable =
>  Mono.fromRunnable(() -> {
>       System.out.println("fromCallable ");
>     }).map(anyVal -> {
>       System.out.println(" in mapping Mapping ");
>       return "any";
>     });
> 
>     fromCallable_.subscribe();
> ```
> 
> prints "fromCallable" only . any help ?

```
Mono.fromRunnable(() -> {
      System.out.println("fromCallable ");
    })
```
this emits no elements, so the map operation will not be executed (no object to be mapped). This is by design.
