### ISSUE TITLE
Need to check example code about the Windowing in the document

### ISSUE THREAD

**Issue by jongmin92** [reactor/reactor-core#2331] opened 2020-08-14 14:35 UTC
## Documentation Issue
The example test code in the documentation failed. Is there a need to fix it?
cc. https://projectreactor.io/docs/core/release/reference/#_windowing_with_fluxfluxt

This is the failing test code from the documentation.
```
StepVerifier.create(
	Flux.just(1, 3, 5, 2, 4, 6, 11, 12, 13)
		.windowWhile(i -> i % 2 == 0)
		.concatMap(g -> g.defaultIfEmpty(-1))
	)
		.expectNext(-1, -1, -1) //respectively triggered by odd 1 3 5
		.expectNext(2, 4, 6) // triggered by 11
		.expectNext(12) // triggered by 13
		// however, no empty completion window is emitted (would contain extra matching elements)
		.verifyComplete();
```

I pass the test after the modification like the following.
```
StepVerifier.create(
	Flux.just(1, 3, 5, 2, 4, 6, 11, 12, 13)
		.windowWhile(i -> i % 2 == 0)
		.concatMap(g -> g.defaultIfEmpty(-1))
	)
		.expectNext(-1, -1, -1)
		.expectNext(2, 4, 6)
		.expectNext(12)
		.expectNext(-1)
		.verifyComplete();
```
Actually I am not understanding why -1 is being generated at the end.

## Improvement Suggestion
If the code is missing in the document(example), I think it needs to be added.

## Additional context
None.

**Comment by jongmin92** [comment] 2020-08-14 15:38
This issue seems to be resolved since the `reactor-core:3.3.0`.

In the above case, I imported `reactor-bom:Bismuth-RELEASE` according to the documentation, so `reactor-core:3.1.0` was automatically used. (https://projectreactor.io/docs/core/release/reference/#_maven_installation)

I noticed the latest BOM file version is `Dysprosium-RELEASE`. and this includes the `reactor-core:3.3.0`.
So I think the version of the BOM file guided by the document should be changed from `Bismuth-RELEASE` to `Dysprosium-RELEASE`.

If the above my suggestion is reasonable, I will make the PR!

**Comment by simonbasle** [comment] 2020-11-02 12:06
careful ! BOMs that are named after the codename (up to `Dysprosium`) use `-RELEASE` for the FIRST release of the cycle, then incremental `-SRxxx` suffixes. So `Bismuth-RELEASE` and `Dysprosium-RELEASE` are respectively the OLDEST releases in the `Bismuth` and `Dysprosium` cycle. We're at `Dysprosium-SR13` as of last week, and we've even released `2020.0.0` (new version scheme, see https://projectreactor.io/docs/core/release/reference/index.html#getting-started-understanding-bom, which should show a more consistent progression: 2020.0.0 < 2020.0.1 < 2020.0.2...)

The `README` of the project is updated on each release, but indeed the reference guide mention of the release train has been overlooked :(

**Comment by simonbasle** [comment] 2020-11-02 12:07
@jongmin92 if you want to contribute a PR, you can do so on branch `3.3.x`, mentioning `Dysprosium-SR13` in all gradle/maven snippets.

**Comment by simonbasle** [comment] 2020-11-02 13:43
mmh actually let me close this one and open a dedicated issue.

**Comment by simonbasle** [comment] 2020-11-02 13:45
Duplicate of #2470

**Closed by simonbasle** 2020-11-02 13:45 UTC
Labels: status/invalid, type/documentation
