### ISSUE TITLE
FluxProcessor never calls onDiscard handler due to the incorrect context

### ISSUE THREAD

**Issue by a701440** [reactor/reactor-core#2387] opened 2020-09-17 14:23 UTC
EmitterProcessor<Item> proc = EmitterProcessor.create(1, false);
Flux<Item> flux = proc.doOnDiscard(Item.class, item-> { System.out.println("Dropped: " + item); });
FluxSink<Item> fluxSink = proc.sink(FluxSink.OverflowStrategy.DROP);

With this kind of setup "System.out.println" is never called when items are dropped due to the overflow.
Looking at the code it appears that the "onDiscard" hook is added to the context:

ctx.put(Hooks.KEY_ON_DISCARD, safeConsumer);

However when FluxProcessor sink is created it gets its context from the actual.currentContext() call on the EmitterProcessor.
And that is always returning an empty context: 

FluxProcessor.currentContext() {
   return Context.empty();
}

And so the hook is never called.

**Comment by simonbasle** [comment] 2020-09-17 14:38
Thanks for reporting. This is a duplicate.
Duplicate of #2356

**Closed by simonbasle** 2020-09-17 14:38 UTC
Labels: :question:need-triage
