### ISSUE TITLE
Error message "Operator called default onErrorDropped" not appropriate

### ISSUE THREAD

**Issue by cyberpunk2025** [reactor/reactor-core#2931] opened 2022-02-22 08:34 UTC
When flux finished with an error. This error message is printed:

16:28:54.371 ERROR [                main] [reactor.core.publisher.Operators] Operator called default onErrorDropped

## Expected Behavior
The error message should not be printed by the framework.

## Actual Behavior
The error message is printed.

## Steps to Reproduce
```java
    @Test
    public void test() throws Exception {
        Flux<Integer> flux = Flux.range(1, 10);

        flux.map(i -> {
                if (i == 5) {
                    throw new RuntimeException("err");
                }
                return i;
            })
            .doOnError(e -> e.printStackTrace())
            .subscribe();
    }
```

## Your Environment
* Reactor version(s) used: 3.4.13

**Comment by cyberpunk2025** [comment] 2022-02-22 08:36
While reactor-core 3.3.11 doesn't print this error message

**Comment by simonbasle** [comment] 2022-02-22 17:52
Duplicate of #2677

**Closed by simonbasle** 2022-02-22 17:52 UTC
Labels: status/duplicate
