### ISSUE TITLE
Memory leak issue with Mono.fromFuture() from 3.4.23+

### ISSUE THREAD

**Issue by hobo05** [reactor/reactor-core#3464] opened 2023-05-17 13:57 UTC
I recently tried to upgrade the reactor libraries in my project and found that the newer versions cause an OOM issue. I have narrowed down the exact version where the OOM issue begins and have sample code that can reproduce this behavior.

## Expected Behavior

When calling `Mono.fromFuture()` multiple times in a chain, memory should be reclaimed after the future completes

## Actual Behavior

`Mono.fromFuture()` causes an OOM when the Java heap max is exceeded and you get an error message `java.lang.OutOfMemoryError: Java heap space`

## Steps to Reproduce

* I recommend running the following code with the VM options `-Xms512m -Xmx512m` in order to trigger the OOM faster
* I wrote 3 different ways of writing in 100MB chunks to a file
  * Synchronously by writing the chunks in a loop
  * Using `CompletableFuture`, but in a lazy way. This was a bit tricky because `CompletableFuture` evaluates eagerly and would cause OOM immediately. However, as you can see, it can be done if you create the bytes at the last minute
  * Using reactor's `Mono.expandDeep()` and `Mono.fromFuture {}` to create a `Flux` of `ByteArray`s and then writing them out to a file

#### Synchronous way,  pure `CompletableFuture`, and `pre-3.4.23` reactor

<img width="147" alt="Screenshot 2023-05-17 at 13 45 27" src="https://github.com/reactor/reactor-core/assets/7526980/a35deec8-88ba-4be8-b2ab-5793354c4152">

#### `3.4.23+` reactor

<img width="120" alt="Screenshot 2023-05-17 at 14 21 19" src="https://github.com/reactor/reactor-core/assets/7526980/2edd87d6-e261-44e4-9e4c-9f241a4badbb">

### Code

```kotlin
import reactor.core.publisher.Mono
import java.io.File
import java.io.FileOutputStream
import java.util.concurrent.CompletableFuture
import java.util.concurrent.CountDownLatch
import java.util.concurrent.atomic.AtomicInteger
import kotlin.math.ceil
import kotlin.random.Random

const val sleepTime = 3000L
fun main() {
    val file = File("bigfile.bin")

    if (file.exists()) {
        file.delete()
    }

    // Get maximum size of heap in bytes.
    val heapMaxSize = Runtime.getRuntime().maxMemory()

    val oneHundredMegaBytes = 1024 * 1024 * 100
    val sections = ceil(heapMaxSize / oneHundredMegaBytes.toDouble()).toInt()
    val doubledSections = sections * 2

    val targetSize = oneHundredMegaBytes
    val targetTimes = doubledSections

    // No futures
//    writeBytesToFileSync(file, targetTimes, targetSize)


    // Use futures, but create byte lazily to not cause OOM
//    writeBytesToFileUsingLazyFutures(targetTimes, file, targetSize)


    // Use Mono.future {}, which should work in 3.4.22, but fails for any of the newer versions
    writeBytesToFileUsingReactor(file, targetSize, targetTimes)

}

private fun writeBytesToFileSync(file: File, targetTimes: Int, targetSize: Int) {
    FileOutputStream(file, true).use { out ->
        (1..targetTimes)
            .forEach { idx ->
                out.write(Random.nextBytes(targetSize))
                println("[Sync] byte array # $idx processed")
                Thread.sleep(sleepTime)
            }
    }
}

private fun writeBytesToFileUsingLazyFutures(targetTimes: Int, file: File, targetSize: Int) {
    (1..targetTimes).fold(CompletableFuture.completedFuture(file)) { fileFuture, idx ->
        fileFuture.thenCompose { curFile ->
            Thread.sleep(sleepTime)
            randomBytesFuture(targetSize).thenApply {
                curFile.appendBytes(it)
                println("[Lazy CompletableFutures] byte array # $idx processed")
                curFile
            }
        }
    }.join()
}

private fun writeBytesToFileUsingReactor(file: File, targetSize: Int, targetTimes: Int) {


    val counter = AtomicInteger(0)

    val latch = CountDownLatch(1)

    Mono.fromFuture { randomBytesFuture(targetSize) }
        .map { counter.incrementAndGet() to it }
        .expandDeep({
            val curCount = counter.incrementAndGet()
            if (curCount > targetTimes)
                Mono.empty()
            else
                Mono.fromFuture { randomBytesFuture(targetSize) }.map { curCount to it }
        }, 1)
        .flatMap {
            Mono.fromRunnable<Unit> {
                Thread.sleep(sleepTime)
                file.appendBytes(it.second)
            }
                .thenReturn(it)
        }
        .subscribe(
            { println("[Mono.fromFuture] byte array # ${it.first} processed") },
            { throwable -> throwable.printStackTrace() },
            {
                println("complete")
                latch.countDown()
            }
        )

    latch.await()
}

fun randomBytesFuture(targetSize: Int): CompletableFuture<ByteArray> = CompletableFuture.supplyAsync {
    println("Creating new random bytes...")
    Random.nextBytes(targetSize)
}
```

## Possible Solution

* The actual PR https://github.com/reactor/reactor-core/pull/3146 that causes this issue is quite simple, but for some reason I cannot figure out how it's possible this small change causes this issue.
* I verified that at least for 3.4.22 to 3.4.23, this was the culprit by checking out 3.4.23 and reverting only the commit for the PR https://github.com/reactor/reactor-core/pull/3146 and that resolved the problem
* Caveat, there was a huge rewrite of `MonoCompletionStage` from this PR https://github.com/reactor/reactor-core/pull/3418 so if a fix is to be found, it isn't simply finding the issue in https://github.com/reactor/reactor-core/pull/3146, we need to find out why the newly written `MonoCompletionStage` also causes a memory leak

### Workaround

1. Upgrade to `3.5.6`
2. Create the `reactor.core.publisher` package to avoid issues with package visibility
3. Grab a copy of a `pre-3.4.23` version of [`MonoCompletionStage`](https://github.com/reactor/reactor-core/blob/5858505e7707f1ea1b75e1ad1b1002aadb8343b7/reactor-core/src/main/java/reactor/core/publisher/MonoCompletionStage.java) and call it something like `LegacyMonoCompletionStage`
4. Write some nasty workaround code

```kotlin
fun <T> legacyFromFuture(futureSupplier: Supplier<out CompletableFuture<out T>?>): Mono<T> {
    return Mono.defer { Mono.onAssembly(LegacyMonoCompletionStage(futureSupplier.get())) }
}
```

## Your Environment

* Reactor version(s) used:
  * `3.4.13` - Works
  * `3.4.22` - Works
  * `3.4.23` - Fails
  * `3.5.1` - Fails
  * `3.5.5` - Fails
  * `3.5.6` - Fails
* Kotlin version: `1.8.20`
* JVM version: `11.0.17-amzn`
* OS and version: `macOS Venture 13.3.1`

**Comment by OlegDokuka** [comment] 2023-05-26 09:12
@hobo05 do you have a memory dump that shows what is leaking? 

So far the only thing which was changed is a link to a Future from the subscription, which probably keeps the reference to a CompletableFuture instance longer than needed, but this is not a memory leak, it is how it works to support cancellation propagation. 

I suspect that the problem is in completableFuture itself which keeps a reference to bytes after completion, hence, once it is done, the memory can be deallocated only by GC and can not be deallocated since we keep reference longer with the recent change. 

I tested your code with the usage of `.onTerminateDetach()` after `fromFuture` as a fix, and so far the problem has been resolved. Feel free to use it as well: 

```java
package reactor;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.atomic.AtomicInteger;

import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import static java.lang.Math.ceil;

public class Test {

	static final long sleepTime = 3000L;

	public static void main(String... args) {
		File file = new File("bigfile.bin");

		if (file.exists()) {
			file.delete();
		}

		// Get maximum size of heap in bytes.
		long heapMaxSize = Runtime.getRuntime()
		                          .maxMemory();

		int oneHundredMegaBytes = 1024 * 1024 * 100;
		int sections = (int) ceil(heapMaxSize / (double) oneHundredMegaBytes);
		int doubledSections = sections * 2;

		int targetSize = oneHundredMegaBytes;
		int targetTimes = doubledSections;

		// No futures
//    writeBytesToFileSync(file, targetTimes, targetSize)

		// Use futures, but create byte lazily to not cause OOM
//    writeBytesToFileUsingLazyFutures(targetTimes, file, targetSize)

		// Use Mono.future {}, which should work in 3.4.22, but fails for any of the newer versions
		Flux.using(() -> new FileOutputStream(file),
				    os -> writeBytesToFileUsingReactor(os, targetSize, targetTimes),
				    os -> {
					    try {
						    os.close();
					    }
					    catch (IOException e) {
						    throw new RuntimeException(e);
					    }
				    })
		    .blockLast();

	}

//	private static void writeBytesToFileSync(File file, int targetTimes, int targetSize) {
//		try (OutputStream out = new FileOutputStream(file, true)) {
//			for (int i = 1; i < targetTimes; i++) {
//				byte[] bytes = new byte[targetSize];
//				ThreadLocalRandom.current()
//				                 .nextBytes(bytes);
//				out.write(bytes);
//				System.out.println("[Sync] byte array" + " #" + " $idx processed");
//				Thread.sleep(sleepTime);
//			}
//		}
//		catch (Throwable t) {
//			throw new RuntimeException(t);
//		}
//	}
//
//	private fun writeBytesToFileUsingLazyFutures(targetTimes:Int,
//			file:File,
//			targetSize:Int) {
//		(1..targetTimes).fold(CompletableFuture.completedFuture(file)) {
//			fileFuture, idx -> fileFuture.thenCompose {
//				curFile -> Thread.sleep(sleepTime) randomBytesFuture(targetSize).thenApply
//				{
//					curFile.appendBytes(it)
//					println("[Lazy CompletableFutures] byte array # $idx processed")
//					curFile
//				}
//			}
//		}.join()
//	}

	private static Flux<byte[]> writeBytesToFileUsingReactor(OutputStream file,
			int targetSize,
			int targetTimes) {

		AtomicInteger counter = new AtomicInteger(0);

		return Mono.fromFuture(() -> randomBytesFuture(targetSize))
		           .map(it -> {
			           counter.incrementAndGet();
			           return it;
		           })
				   .onTerminateDetach()
		           .expandDeep(it -> {
			           int curCount = counter.incrementAndGet();
			           if (curCount > targetTimes) {
				           return Mono.empty();
			           }
			           else {
				           return Mono.fromFuture(() -> randomBytesFuture(targetSize))
				                      .onTerminateDetach();
			           }
		           }, 1)
		           .flatMap(it -> Mono.fromCallable(() -> {
			                              Thread.sleep(sleepTime);
			                              file.write(it);
			                              return null;
		                              })

		                              .thenReturn(it));
	}

	static CompletableFuture<byte[]> randomBytesFuture(int targetSize) {
		return CompletableFuture.supplyAsync(() -> {
			System.out.println("Creating new random bytes...");
			byte[] bytes = new byte[targetSize];
			ThreadLocalRandom.current()
			                 .nextBytes(bytes);
			return bytes;
		});
	}
}
```

**Comment by OlegDokuka** [comment] 2023-05-26 19:36
closing since the observed behavior is expected (it was a bug that CompletableFuture did not receive cancel signal) as well as this issue has a workaround

**Closed by OlegDokuka** 2023-05-26 19:36 UTC
Labels: status/invalid, status/has-workaround

**Comment by hobo05** [comment] 2023-05-30 08:45
Thanks @OlegDokuka, `.onTerminateDetach()` indeed fixes this issue so we don't have to use the workaround!

Some clarifying points:

`Mono.fromFuture(supplier, supperCancellation=true)` does not actually fix the problem as you can see below.

<img width="883" alt="Screenshot 2023-05-30 at 09 40 04" src="https://github.com/reactor/reactor-core/assets/7526980/b1b744a5-21e2-44cb-ae4f-6baf987a664d">

Regarding `ByteBuf`, the original code that was causing the error in the `Mono.expandDeep` was using the AWS SDK with an underlying `NettyNioAsyncHttpClient`. I could see `ByteBuf` being used in the flame graphs, but perhaps the there's something else happening that I'm not aware of that causes this.

```kotlin
            athenaAsyncClient.getQueryResults { it
                .queryExecutionId(queryExecutionId)
                .maxResults(pageSize)
                .nextToken(nextToken)
            }
```

In any case, I am more than happy with the outcome of this ticket and not having to use the workaround. Thank you very much!!
