### ISSUE TITLE
Flux merge operator does not propagate error from mono

### ISSUE THREAD

**Issue by Dariusz91** [reactor/reactor-core#1941] opened 2019-11-05 06:49 UTC
Hi! We've noticed a problem with Flux merge operator. In our case we're creating Flux by merging two Monos - first emits one element and second emits error. We expect that in this case Flux will emit error after merge. In most cases it is true, but sometimes it ends up with success. We've noticed that it happens when Monos were executed on different threads. We would be grateful if you could look into it.

## Expected Behavior
In our opinion when we merge multiple Monos and one of them emits error then whole Flux should return error in every case.

## Actual Behavior
From time to time when we create Flux by merging Monos (monos are executed on different threads) and one of them emits error then whole Flux emits element from successfully completed Mono.

Interesting logs fragment from sample project (link to project in section below)
```
11:50:46.945 [parallel-4] INFO pl.test.reactor.MergeOperatorSpec - Second Mono Success: abc
11:50:46.945 [parallel-3] ERROR pl.test.reactor.MergeOperatorSpec - First Mono Error
java.lang.RuntimeException: X
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
	at pl.test.reactor.MergeOperatorSpec$_monoWithError_closure1.doCall(MergeOperatorSpec.groovy:65)
	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:122)
	at com.sun.proxy.$Proxy23.apply(Unknown Source)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:199)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoDelayElement$DelayElementSubscriber.lambda$onNext$0(MonoDelayElement.java:123)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
11:50:46.946 [parallel-4] INFO pl.test.reactor.MergeOperatorSpec - Flux Success
```

## Steps to Reproduce
Use test from project [https://github.com/Dariusz91/merge_operator](https://github.com/Dariusz91/merge_operator)
Unfortunately test is nondeterministic (I wasn't able to reproduce it in deterministic way) - you should run it multiple times (script attached to project can help with that)

## Possible Solution
?

## Your Environment

* Reactor version(s) used: 3.3.0.RELEASE
* JVM version (`javar -version`): openjdk version "11.0.2" 2019-01-15, OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
* OS and version (eg `uname -a`): Darwin 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

**Comment by simonbasle** [comment] 2019-11-05 09:55
I cannot reproduce this. I have run the below test, adapted from your code, 68 000 times without a failure:

```java
@Test
public void gh1941() throws InterruptedException {
	Mono<String> first = Mono.just("foo")
	                         .delayElement(Duration.ofMillis(5))
			.<String>map(v -> { throw new RuntimeException("foo"); })
//				.doOnError(e -> System.out.println("First mono error " + e))
			.doOnSuccess(v -> System.out.println("First mono success " + v));


	Mono<String> second = Mono.just("abc")
	                          .delayElement(Duration.ofMillis(10))
	                          .doOnError(e -> System.out.println("Second mono error " + e));
//		                          .doOnSuccess(v -> System.out.println("Second mono success " + v));

	AtomicInteger errorCounter = new AtomicInteger();

	for (int i = 0; i < 5; i++) {
		CountDownLatch latch = new CountDownLatch(1);

		Flux.merge(first, second)
		    .then(Mono.empty())
		    .doOnError(e -> {
//				    System.out.println("Flux Error");
			    errorCounter.incrementAndGet();
		    })
		    .doOnSuccess(v -> System.out.println("Flux Success"))
		    .doOnTerminate(latch::countDown)
		    .subscribe();

		latch.await(1, TimeUnit.SECONDS);
	}
	assertThat(errorCounter.get()).isEqualTo(5);
}
```

**Comment by akarnokd** [comment] 2019-11-05 10:29
5 and 10 milliseconds are really close on many operating systems so you are racing an error with a non-error source. You have to decide what kind of outcome you want and pick a different operator. For example, wait for both: `zip`, get all success values before error: `mergeDelayError`.

**Comment by simonbasle** [comment] 2019-11-05 10:52
ah @akarnokd thanks for pointing that out! I totally forgot that `merge` could short-circuit on an `onError` signal 🤦‍♂

**Comment by Dariusz91** [comment] 2019-11-05 12:24
Yes, it should short circuit on error signal from Mono and in this case we're expecting error from whole Flux. 
In attached logs, an other situation had occurred - first log is about success from Mono and the second is about error from other Mono. Shouldn't whole Flux wait for completion signal from the latter before executing then() and logging "Flux success"? (We're expecting error in this case, not success)

**Comment by arunim29** [comment] 2020-09-16 19:50
@akarnokd can the race condition cause the merged flux to ignore error signal from the first mono and complete with a success?

**Comment by GeorgiPetkov** [comment] 2021-02-27 18:21
Hi! I've been strugling with this issue for several hours now. IMO there's definitely a race condition and I have a test reproducing it. I hope it will execute as consitently for you as it is for me.
My use case was using `PipedInputStream` and `PipedOutputStream` which by design have to run in different threads. What I wanted is to use limited in-memory buffer and as soon as enough data is produced (in my case pdf generation) I can stream it over the network. 
I've greatly simplified the code and removed everything irrelevant to produce the following test:

````java
package com.finrax.document.generator.pdf;

import org.junit.jupiter.api.Test;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.core.scheduler.Schedulers;
import reactor.test.StepVerifier;

import java.io.*;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

class FluxMergeTest {

    @Test
    void test() throws IOException {
        PipedInputStream inputStream = new PipedInputStream();
        PipedOutputStream outputStream = new PipedOutputStream(inputStream);

        StepVerifier.create(
                Flux.merge(
                        Mono.using(
                                () -> outputStream,
                                output -> Mono.fromRunnable(FluxMergeTest::simulateWorkAndThenThrow),
                                FluxMergeTest::close)
                                .subscribeOn(Schedulers.parallel()),
                        Mono.using(
                                () -> inputStream,
                                input -> Mono.fromRunnable(() -> waitStreamEnd(input)),
                                FluxMergeTest::close)
                                .subscribeOn(Schedulers.parallel())))
                .verifyError(ExpectedException.class);
    }

    private static class ExpectedException extends RuntimeException {
    }

    private static void simulateWorkAndThenThrow() {
        assertDoesNotThrow(() -> Thread.sleep(1000));
        throw new ExpectedException();
    }

    private static void waitStreamEnd(InputStream input) {
        assertDoesNotThrow(input::readAllBytes);
    }

    private static void close(Closeable closeable) {
        assertDoesNotThrow(closeable::close);
    }
}
```

The reason why this is a good example is because the 2 monos are dependent. The second always completes and does so only when the first is about to terminate. In this case the first always terminates with an error. The delay (through `Thread.sleep`) is necessary to give some time for the second subscription to happen. The fact that for monos the `using` method first closes the resource and then emits terminating signal is also helping.
The test will fail only the first time (if changed to run as `@RepeatedTest`). This is due to having to load some classes lazying the first time. This can be proven by slowing down the code a bit. For example if you change line `assertDoesNotThrow(input::readAllBytes);` to `assertArrayEquals(new byte[0], assertDoesNotThrow(input::readAllBytes));` the test will succeed more often than not (but still fails ~5-10% of the times).
FYI I'm running the test using the latest version of Intellij and Java 15.

**Comment by simonbasle** [comment] 2021-03-01 17:55
Thanks for the reproducer. I now can also reproduce it fairly easily with the following unit test:

```java
    @Test
	void completeVsError() throws InterruptedException {
		//for (int i = 0; i < 1000; i++) {
			AtomicInteger terminalState = new AtomicInteger();
			AtomicReference<Subscriber<? super Integer>> sub1 = new AtomicReference<>();
			AtomicReference<Subscriber<? super Integer>> sub2 = new AtomicReference<>();

			CountDownLatch latch = new CountDownLatch(1);
			Flux.merge((Publisher<Integer>) sub1::set, (Publisher<Integer>) sub2::set)
			    .subscribe(v -> {},
					    err -> {
						    terminalState.addAndGet(10);
						    latch.countDown();
					    },
					    () -> {
						    terminalState.addAndGet(100);
						    latch.countDown();
					    });

			RaceTestUtils.race(
					() -> sub1.get().onComplete(),
					() -> sub2.get().onError(new IllegalStateException("expected"))
			);

			assertThat(latch.await(10, TimeUnit.SECONDS)).as("latch in round " + i).isTrue();
			assertThat(terminalState).withFailMessage("expected onError, got %s in round %s", terminalState, i).hasValue(10);
		//}
	}
```

I had a jcStress test reproducing it as well. @akarnokd it seems RxJava isn't susceptible to this bug, but that's not a big surprise seeing how much the two codebases have diverged.

I suspect the `checkTerminated` implementation and/or usage to be the root cause, but so far without hard evidence nor fix. I was able to make the above test "pass"... but to the expense of other tests hanging because now they don't receive `onComplete` at all 🤒

Continuing the investigation on that one.

**Closed** 2021-03-02 16:18 UTC
Labels: status/need-investigation, type/bug
