### ISSUE TITLE
 Race condition in .bufferUntil causing "Could not emit buffer due to lack of requests"

### ISSUE THREAD

**Issue by benwiles1** [reactor/reactor-core#1937] opened 2019-11-01 22:16 UTC
## Expected Behavior

`.bufferUntil` should not be able to cause "Could not emit buffer due to lack of requests" since it is deterministic, and not based on the rate of the subscriber like in `.bufferTimeout`.

## Actual Behavior

`.bufferUntil` threw "Could not emit buffer due to lack of requests"

## Steps to Reproduce

```java
package test;

import java.time.Duration;

import reactor.core.publisher.Flux;
import reactor.core.publisher.Hooks;
import reactor.core.publisher.Mono;

public class Test {
    public static void main(String[] args) {
        Hooks.onOperatorDebug();
        Flux.range(0, 1000)
                .bufferUntil(v -> true)
                .flatMap(v -> Mono.delay(Duration.ofMillis(10)))
                .blockLast();
    }
}
```

## Your Environment

* Reactor version(s) used: 3.3.0.RELEASE
* Other relevant libraries versions (eg. `netty`, ...): none
* JVM version (`javar -version`): JDK 11
* OS and version (eg `uname -a`): Windows 10

**Comment by bsideup** [comment] 2019-11-18 10:01
Adding "onOperatorDebug" because, without the hook applied, it does not seem to fail

**Comment by bsideup** [comment] 2019-11-18 14:07
Short update: managed to reproduce without `Hooks.onOperatorDebug()`

**Comment by UgiR** [comment] 2020-01-25 20:26
For every buffer emission, REQUESTED in decremented.

When a request comes in for n buffers, multiple emissions can occur before REQUESTED in properly updated to reflect.

So while the loop in `DrainUtils.postCompleteRequest` is constantly failing to get a grasp on `REQUESTED` and update it with n, `emit()` is emitting buffers and decrementing `REQUESTED` until it hits -1.

Putting the call to `postCompleteRequest()` in `request()` seems to fix this but I'm not sure why or what a good approach to fixing this would be.

**Comment by UgiR** [comment] 2020-01-27 18:17
Hmm, maybe there's more to it. Here's a reproducer that fails reliably even when the update to REQUESTED is in a synchronized block. Note that changing flatMap's concurrency to 1 will allow the test to pass.
```
@Test
public void requestedCountContentionRaceCondition() {
	Mono<Void> source = Flux.range(0, 1000)
			.bufferUntil(i -> true)
			.limitRate(3)
			.flatMap(i -> Mono.delay(Duration.ofMillis(1)), 16)
			.then();

	StepVerifier.create(source)
			.verifyComplete();
}
```

**Comment by robotmrv** [comment] 2020-01-28 23:44
I've able to reproduce similar behavior with totally synchronous code  
```java
Flux.just(0, 1, 2)
        .bufferUntil(s -> true)
        .limitRate(1)
        .subscribe(new BaseSubscriber<Object>() {
            @Override
            protected void hookOnSubscribe(Subscription subscription) {
                subscription.request(1);
            }
        });
```
It reproduces if there is operator with prefetch downstream the bufferUntil()  

As far as i understand problem appears when `reactor.core.publisher.FluxBufferPredicate.BufferPredicateSubscriber#request` is invoked indirectly from or in parallel with `reactor.core.publisher.FluxBufferPredicate.BufferPredicateSubscriber#emit` and subscriber has limited demand.

I have naive fix for this :)  
in reactor.core.publisher.FluxBufferPredicate.BufferPredicateSubscriber
```java
boolean emit(C b) {
    if (fastpath) {
        actual.onNext(b);
        return false;
    }
    long r = REQUESTED.getAndDecrement(this);
    if(r > 0){
        boolean requestMore = r - 1 > 0;// just move return requested > 0 check before onNext()
        actual.onNext(b);
        return requestMore;//return requested > 0;
    }
    cancel();
    actual.onError(Exceptions.failWithOverflow("Could not emit buffer due to lack of requests"));
    return false;
}
```

**Comment by simonbasle** [comment] 2020-02-03 10:30
Thanks for investigating @UgiR and @robotmrv 👍

**Closed** 2020-02-17 19:19 UTC
Labels: type/bug
