### ISSUE TITLE
Flux.flatMapIterable "steals" threads of downstream publishOn operator.

### ISSUE THREAD

**Issue by mlex** [reactor/reactor-core#2191] opened 2020-06-15 08:14 UTC
Given a processing pipeline like 
```
flux
  .publishOn(Schedulers.newParallel("process"))
  .flatMapIterable(this::process)
  .publishOn(Schedulers.newParallel("downstream"))
  .subscribe(this::downstream)
```
it can happen that the `process` method is actually executed on the "downstream" scheduler.

In our case, this became a throughput bottleneck, because the "process" step was actually heavy work (deserializing json, executing various regular expressions) and was parallelized using `Flux.parallel().runOn()`. The downstream work was very fast but was required to be executed sequentially. 

The thread stealing lead to a situation where the heavy work was done on a single sequential "downstream" thread while all the paralel "process" threads were waiting and doing nothing.

## Steps to Reproduce
A test case that reproduces the problem: https://gist.github.com/mlex/fc4866ec131785968ead83d8ca16e4e7

The stacktrace shows, that the `request()` which is called inside the `PublishOnSubscriber.runAsync` method (which is running on the downstream scheduler) is the root cause for this behaviour. The FlattenIterableSubscriber synchronously emits elements when a downstream subscriber requests. So together this leads to a situation where the flatMapIterable work is actually then executed on the downstream scheduler.

```
java.lang.RuntimeException: This should not run on a 'downstream' thread
	at ReactorThreadStealingTest.process(ReactorThreadStealingTest.java:44)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:341)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:649)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.request(FluxFlattenIterable.java:273)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:405)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:484)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```
## Possible Solution

I'm not sure if this is really a bug or just unexpected behaviour or if we are just "using it wrong". At the moment we avoid using "publishOn" after a "flatMapIterable" (or any other operator has a queue - which extremely limits the number of allowed operators).

Our current workarounds are either completely avoiding the second publishOn:
```
  .publishOn(Schedulers.newParallel("process"))
  .flatMapIterable(this::process)
  .subscribe(this::downstream)
```

or moving the `flatMapIterable` after the `publishOn`:
```
  .publishOn(Schedulers.newParallel("process"))
  .map(this::process)
  .publishOn(Schedulers.newParallel("downstream"))
  .flatMapIterable(iterable -> iterable)
  .subscribe(this::downstream)
```

## Your Environment
* Reactor version used: 3.3.6.RELEASE
* JVM version (`javar -version`): 1.8.0_252

**Comment by bsideup** [comment] 2020-06-15 08:52
@mlex as a general rule, we commend never assuming the scheduling and always be explicit. Work stealing is a common pattern in reactive frameworks, and it is absolutely valid to have `flatMapIterable` running on the downstream thread. **There is no problem with that**.

The problem happens when you run blocking code in `flatMapIterable` - _something you should never do._ Instead, you should explicitly define (via `publishOn` before `flatMapIterable`) a `Scheduler` that should be running `flatMapIterable`'s mapper.

**Comment by mlex** [comment] 2020-06-15 09:18
Hi  @bsideup. Thank you for the quick response. 

> always be explicit.
That's what I did. I explicitly used `publishOn`.

> Work stealing is a common pattern in reactive frameworks
I know work stealing in operators like `merge`, where downstream tasks can run on an arbitrary upstream scheduler (whichever triggered the drain loop). And I know that this can be avoided by using `publishOn` to force downstream work to be done on an explicitly defined scheduler.

However in the outlined situation, an upstream operator is running tasks on a scheduler that's defined downstream. That's unexpected. And worse: there is no way to avoid it. 

> The problem happens when you run blocking code in flatMapIterable.
I did not run any blocking code in the flatMapIterable. I ran heavy computation (deserializing, pattern matching). That should be allowed inside flatMapIterable, isn't it?

> Instead, you should explicitly define (via publishOn before flatMapIterable) a Scheduler that should be running flatMapIterable's mapper.
That's exactly what I did. I explicitly put a `publishOn(Schedulers.newParallel("process"))` before the `flatMapIterable`. But the problem is, that the `flatMapIterable` sometimes gets executed on the downstream scheduler!

**Comment by bsideup** [comment] 2020-06-15 09:21
@mlex sorry, I did not look carefully enough at the reproducer and missed the `publishOn` before `flatMapIterable`, which is indeed weird.

> I did not run any blocking code in the flatMapIterable. I ran heavy computation (deserializing, pattern matching). That should be allowed inside flatMapIterable, isn't it?

Yes, computations are fine 👍 I just noticed `LockSupport.parkNanos(100_000);` in `process`, hence my note about the blocking code.

**Comment by simonbasle** [comment] 2020-06-15 09:37
I'm not sure exactly what happens, some race condition maybe?
`flatMapIterable` doesn't seem to cope well with a fast unbackpressured producer and a slow iterable transformer, which is arguably the worst scenario out there.

But I think the `map`-then-`publishOn`-then-`flatMap` approach is a good workaround. Another workaround could be to do `.flatMap(v -> Flux.fromIterable(process(v)))`

**Comment by mlex** [comment] 2020-06-15 11:16
The `publishOn` operator calls `request()` on the "downstream" thread.

The `flatMapIterable` implementataion of the `request()` simply calls `drain()`. If there is not already a `drain` running on another thread, then this drain call leads to the mentioned behaviour (mapper-function being executed on the downstream thread). So yes, it is kind of a race condition: the `request` must happen while there is currently no other `drain` execution running.

The following variations show the same behaviour:
```
flux
  .publishOn(Schedulers.newParallel("process"))
  .flatMap(v -> Flux.fromIterable(process(v)))
  .publishOn(Schedulers.newParallel("downstream"))

flux
  .publishOn(Schedulers.newParallel("process"))
  .map(this::process)
  .flatMapIterable(iterable -> iterable)
  .publishOn(Schedulers.newParallel("downstream"))
```

From a pure logical viewpoint, I think the `flatMapIterable` is behaving just as it should. It receives a new request from downstream. It has unprocessed elements in its queue. So it immediately starts processing and emitting new elements. And it also requests elements from upstream. And if upstream operators also emit synchronously. All this happens synchronously on the thread where the initial request is made.

Generally, there are some operators that can synchronously emit elements when receiving request from downstream (like `flatMapIterable`). Other operators like `publishOn` always emit on a specified scheduler.

Is this behaviour intended? If not, then perhaps the `publishOn` operator could allow defining a separate `requestScheduler`. Similar to the `request-task` thread that's created for the `TopicProcessor`.

**Comment by mlex** [comment] 2020-06-16 15:55
To illustrate my suggestion, here is a first try at an implementation of such a "request scheduler" for the `publishOn` operator: https://github.com/mlex/reactor-core/commit/b649631694592a315071c9a45cee152e40500cd1

The default behaviour is not changed. But users who want to make sure that the scheduler is only ever used for downstream work (and never stolen by upstream processing steps), they can define an additional `requestScheduler`.

Of course this has an impact on performance, because of the additional scheduling of the `requestMore` task. And also because of additional scheduling of the `run` task, because it's more likely that the run-loop terminates and must be re-scheduled when the next elements arrive - which is not the case when upstream publishers can emit elements synchronously when requested.

**Comment by simonbasle** [comment] 2020-10-28 13:52
Since there is a workaround, I'm inclined to close this issue. From what I can see, your suggestion with the `requestScheduler` looks a lot like what `subscribeOn` does. Wouldn't that be another option @mlex ?

**Comment by mlex** [comment] 2020-10-28 14:08
Wow. I didn't know that `subscribeOn` also runs all `request` calls on the specified scheduler. That's exactly what I was looking for. Thank you!

The following should then do exactly what I want: it runs the `this::process` method only on the specified `processScheduler` (no matter if the processing was triggered by an onNext signal from upstream or by a `request` from downstream).
```
Scheduler processScheduler = Schedulers.newParallel("process");
flux
  .publishOn(processScheduler)
  .flatMapIterable(this::process)
  .subscribeOn(processScheduler)
  .publishOn(Schedulers.newParallel("downstream"))
  .subscribe(this::downstream)
```

Yes, you can close the issue.

**Comment by simonbasle** [comment] 2020-10-28 16:11
awesome ! glad this works out for your case 👍

**Closed by simonbasle** 2020-10-28 16:11 UTC
Labels: for/user-attention, status/has-workaround, status/need-investigation
