### ISSUE TITLE
Dropped Errors on Multicast & Merge

### ISSUE THREAD

**Issue by jGleitz** [reactor/reactor-core#2857] opened 2021-12-17 14:52 UTC
## Expected Behavior
When I multicast a `Flux` and merge the multicasted fluxes together again, everything ‘just works’.

## Actual Behavior
If the multicasted `Flux` send an error, the error is dropped once.

## Steps to Reproduce

```java
    @Test
    void multicastAndMerge() {
        var multicast = Flux.<Integer>error(new IllegalArgumentException()).publish().refCount(2);
        var merged = multicast
            .map(it -> it * 2)
            .mergeWith(
                multicast
                    // imagine some long-running task here
                    .flatMap(it -> Mono.just(it + 2))
            );
        StepVerifier.create(merged)
            .expectError(IllegalArgumentException.class)
            .verifyThenAssertThat()
            .hasNotDroppedErrors();
    }
```

```
java.lang.AssertionError: Expected no dropped errors, found <[java.lang.IllegalArgumentException]>.

	at reactor.test.MessageFormatter.assertionError(MessageFormatter.java:115)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifierAssertions.satisfies(DefaultStepVerifierBuilder.java:1831)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifierAssertions.hasNotDroppedErrors(DefaultStepVerifierBuilder.java:1930)
        […]
```

## Background
I have the following use case: My server receives a stream of requests and sends a stream of response messages. For every request, there are some messages that can be calculated ‘directly’ (meaning that they require network calls, but that they are triggered directly by the request). Additionally, there are response messages that are triggered by other events, where the requests only determine which of these messages will be relayed. 

My solution is hence to multicast the requests, send one of the versions to the ‘direct responses’ producer, and the other to the ‘async responses’ producer. Then I merge together the two result `Flux`es. As far as I can see, this has the desired effect in the happy case. However, in an error case, I get the reported dropped error.

I could not find anything stating that multicasting & merging together in this way is not allowed. Hence, I consider this a bug. If I violated some contract that I am not aware of, please point me towards it.

## Your Environment

* Reactor version(s) used: 3.4.12
* Other relevant libraries versions (eg. `netty`, ...): none
* JVM version (`java -version`): 
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
Eclipse OpenJ9 VM AdoptOpenJDK-11.0.11+9 (build openj9-0.26.0, JRE 11 Linux amd64-64-Bit Compressed References 20210421_975 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 7796c80419 based on jdk-11.0.11+9)
```

* OS and version (eg `uname -a`):
```
Linux Lovelace 5.13.0-22-generic #22-Ubuntu SMP Fri Nov 5 13:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by OlegDokuka** [comment] 2021-12-27 17:51
@jGleitz, unfortunately, we can do nothing about it, what your described as actual is by fact expected behavior and they never are changes for the mentioned example.

Broadcasted, or shared Flux, which is then merged back in a single stream, at its joining point does not perform any complex analysis, which can suggest that both streams are from the same source. **Why**? - because it makes no sense: 1 - it is expensive to do for short running streams, 2 - it is unclear what to do if operations that change the flow in a non-linear way (e.g. any operation which has complexity higher than in `.map` - such as any flatten related transformation) are present in one or the other derived sub-flows. That says a straightforward tool such as Project Reactor is not designed to solve any complicated optimization problems and perform runtime analysis to eliminate some minor redundancy (e.g. error doubling in share -> merge scenario).

Just in case the mentioned behaviors are annoying from the logging perspective, I would suggest considering using `Hooks.onErrorDropped(error -> {})` hook which can catch all dropped error without reporting them to the logger

**Closed by OlegDokuka** 2021-12-27 17:51 UTC
